#include"AdApter_CrossingObject_PUB.h"

void print_memory(const void* ptr, size_t size) {
    const unsigned char* bytes = static_cast<const unsigned char*>(ptr);
    for (size_t i = 0; i < size; ++i) {
        std::cout << std::hex << std::setw(2) << std::setfill('0') 
                  << static_cast<int>(bytes[i]) << " ";
    }
    std::cout << std::dec << std::endl;
}






AdApter_CrossingObjectPUB::AdApter_CrossingObjectPUB()
{
}
AdApter_CrossingObjectPUB::~AdApter_CrossingObjectPUB()
{
}
auto AdApter_CrossingObjectPUB::maxeye_midware_init()
{

return proto_info;
}


void AdApter_CrossingObjectPUB::run()
{
    int i=0;
    std::cout << "config file path: " << json_file.c_str() << std::endl;
    data_in.resize(sizeof(CrossingObject));
    MOS::communication::Init(json_file.c_str());
    MOS::utils::Register::get().register_version("libCrossingObjectPUB", "1.1.0");
    MOS::communication::ProtocolInfo proto_info;
    proto_info.protocol_type = MOS::communication::kProtocolShm;//kProtocolHybrid
    proto_info.shm_info.block_count = 10;
    proto_info.shm_info.block_size = data_in.size();
    proto_info.shm_info.fast_mode = false;
    auto pub = MOS::communication::Publisher::New(domiain_id, topic, proto_info);
    auto mos_msg = std::make_shared<MOS::message::Message>();
    std::this_thread::sleep_for(std::chrono::milliseconds(cycle_ms*3));//40ms


    CrossingObject CrossingObject_;
    setIntialValue_CrossingObject(CrossingObject_);

    while (true) {        
        data_in.resize(sizeof(CrossingObject_));
        std::memcpy(&data_in[0], &CrossingObject_, sizeof(CrossingObject_));
        auto data_ref = std::make_shared<MOS::message::DataRef>(const_cast<char*>(data_in.data()), data_in.size());
        mos_msg->SetDataRef(data_ref);
        auto now_time = MOS::TimeUtils::NowNsec();
        mos_msg->SetGenTimestamp(now_time);
        pub->Pub(mos_msg);
        std::this_thread::sleep_for(std::chrono::milliseconds(cycle_ms));//40ms
    }
}
int main()
{
#ifdef _WIN32
    char* path = nullptr;
    _get_pgmptr(&path);
    std::stringstream ss;
    ss << path;
    std::string fullPath(path);
    std::cout << "Running on Windows" << std::endl;
#endif
#ifdef __linux__
    std::string fullPath = std::filesystem::read_symlink("/proc/self/exe");
    std::cout << "Running CrossingObject_PUB on Linux"<< fullPath << std::endl;
#endif
    size_t pos = fullPath.find_last_of("\\/");
    std::string configPath = fullPath.substr(0, pos) + "/discovery_config.json";
    AdApter_CrossingObjectPUB objtest;
    objtest.json_file = configPath;
    objtest.run();
return 0;
}





/* Set and Print struct CrossingObject initial value */
void setIntialValue_CrossingObject(CrossingObject& CrossingObject_){
    std::cout << "Set struct CrossingObject variable and Publish:" << std::endl;
    CrossingObject_.EgoStates[0].latAcceleration = 1.10;
    std::cout << "CrossingObject_.EgoStates[0].latAcceleration(float32): " << CrossingObject_.EgoStates[0].latAcceleration << std::endl;
    CrossingObject_.EgoStates[0].longAcceleration = 2.20;
    std::cout << "CrossingObject_.EgoStates[0].longAcceleration(float32): " << CrossingObject_.EgoStates[0].longAcceleration << std::endl;
    CrossingObject_.EgoStates[0].latPosition = 3.30;
    std::cout << "CrossingObject_.EgoStates[0].latPosition(float32): " << CrossingObject_.EgoStates[0].latPosition << std::endl;
    CrossingObject_.EgoStates[0].longPosition = 4.40;
    std::cout << "CrossingObject_.EgoStates[0].longPosition(float32): " << CrossingObject_.EgoStates[0].longPosition << std::endl;
    CrossingObject_.EgoStates[0].latVelocity = 5.50;
    std::cout << "CrossingObject_.EgoStates[0].latVelocity(float32): " << CrossingObject_.EgoStates[0].latVelocity << std::endl;
    CrossingObject_.EgoStates[0].longVelocity = 6.60;
    std::cout << "CrossingObject_.EgoStates[0].longVelocity(float32): " << CrossingObject_.EgoStates[0].longVelocity << std::endl;
    CrossingObject_.EgoStates[1].latAcceleration = 7.70;
    std::cout << "CrossingObject_.EgoStates[1].latAcceleration(float32): " << CrossingObject_.EgoStates[1].latAcceleration << std::endl;
    CrossingObject_.EgoStates[1].longAcceleration = 8.80;
    std::cout << "CrossingObject_.EgoStates[1].longAcceleration(float32): " << CrossingObject_.EgoStates[1].longAcceleration << std::endl;
    CrossingObject_.EgoStates[1].latPosition = 9.90;
    std::cout << "CrossingObject_.EgoStates[1].latPosition(float32): " << CrossingObject_.EgoStates[1].latPosition << std::endl;
    CrossingObject_.EgoStates[1].longPosition = 11.00;
    std::cout << "CrossingObject_.EgoStates[1].longPosition(float32): " << CrossingObject_.EgoStates[1].longPosition << std::endl;
    CrossingObject_.EgoStates[1].latVelocity = 12.10;
    std::cout << "CrossingObject_.EgoStates[1].latVelocity(float32): " << CrossingObject_.EgoStates[1].latVelocity << std::endl;
    CrossingObject_.EgoStates[1].longVelocity = 13.20;
    std::cout << "CrossingObject_.EgoStates[1].longVelocity(float32): " << CrossingObject_.EgoStates[1].longVelocity << std::endl;
    CrossingObject_.EgoStates[2].latAcceleration = 14.30;
    std::cout << "CrossingObject_.EgoStates[2].latAcceleration(float32): " << CrossingObject_.EgoStates[2].latAcceleration << std::endl;
    CrossingObject_.EgoStates[2].longAcceleration = 15.40;
    std::cout << "CrossingObject_.EgoStates[2].longAcceleration(float32): " << CrossingObject_.EgoStates[2].longAcceleration << std::endl;
    CrossingObject_.EgoStates[2].latPosition = 16.50;
    std::cout << "CrossingObject_.EgoStates[2].latPosition(float32): " << CrossingObject_.EgoStates[2].latPosition << std::endl;
    CrossingObject_.EgoStates[2].longPosition = 17.60;
    std::cout << "CrossingObject_.EgoStates[2].longPosition(float32): " << CrossingObject_.EgoStates[2].longPosition << std::endl;
    CrossingObject_.EgoStates[2].latVelocity = 18.70;
    std::cout << "CrossingObject_.EgoStates[2].latVelocity(float32): " << CrossingObject_.EgoStates[2].latVelocity << std::endl;
    CrossingObject_.EgoStates[2].longVelocity = 19.80;
    std::cout << "CrossingObject_.EgoStates[2].longVelocity(float32): " << CrossingObject_.EgoStates[2].longVelocity << std::endl;
    CrossingObject_.EgoStates[3].latAcceleration = 20.90;
    std::cout << "CrossingObject_.EgoStates[3].latAcceleration(float32): " << CrossingObject_.EgoStates[3].latAcceleration << std::endl;
    CrossingObject_.EgoStates[3].longAcceleration = 22.00;
    std::cout << "CrossingObject_.EgoStates[3].longAcceleration(float32): " << CrossingObject_.EgoStates[3].longAcceleration << std::endl;
    CrossingObject_.EgoStates[3].latPosition = 23.10;
    std::cout << "CrossingObject_.EgoStates[3].latPosition(float32): " << CrossingObject_.EgoStates[3].latPosition << std::endl;
    CrossingObject_.EgoStates[3].longPosition = 24.20;
    std::cout << "CrossingObject_.EgoStates[3].longPosition(float32): " << CrossingObject_.EgoStates[3].longPosition << std::endl;
    CrossingObject_.EgoStates[3].latVelocity = 25.30;
    std::cout << "CrossingObject_.EgoStates[3].latVelocity(float32): " << CrossingObject_.EgoStates[3].latVelocity << std::endl;
    CrossingObject_.EgoStates[3].longVelocity = 26.40;
    std::cout << "CrossingObject_.EgoStates[3].longVelocity(float32): " << CrossingObject_.EgoStates[3].longVelocity << std::endl;
    CrossingObject_.EgoStates[4].latAcceleration = 27.50;
    std::cout << "CrossingObject_.EgoStates[4].latAcceleration(float32): " << CrossingObject_.EgoStates[4].latAcceleration << std::endl;
    CrossingObject_.EgoStates[4].longAcceleration = 28.60;
    std::cout << "CrossingObject_.EgoStates[4].longAcceleration(float32): " << CrossingObject_.EgoStates[4].longAcceleration << std::endl;
    CrossingObject_.EgoStates[4].latPosition = 29.70;
    std::cout << "CrossingObject_.EgoStates[4].latPosition(float32): " << CrossingObject_.EgoStates[4].latPosition << std::endl;
    CrossingObject_.EgoStates[4].longPosition = 30.80;
    std::cout << "CrossingObject_.EgoStates[4].longPosition(float32): " << CrossingObject_.EgoStates[4].longPosition << std::endl;
    CrossingObject_.EgoStates[4].latVelocity = 31.90;
    std::cout << "CrossingObject_.EgoStates[4].latVelocity(float32): " << CrossingObject_.EgoStates[4].latVelocity << std::endl;
    CrossingObject_.EgoStates[4].longVelocity = 33.00;
    std::cout << "CrossingObject_.EgoStates[4].longVelocity(float32): " << CrossingObject_.EgoStates[4].longVelocity << std::endl;
    CrossingObject_.EgoStates[5].latAcceleration = 34.10;
    std::cout << "CrossingObject_.EgoStates[5].latAcceleration(float32): " << CrossingObject_.EgoStates[5].latAcceleration << std::endl;
    CrossingObject_.EgoStates[5].longAcceleration = 35.20;
    std::cout << "CrossingObject_.EgoStates[5].longAcceleration(float32): " << CrossingObject_.EgoStates[5].longAcceleration << std::endl;
    CrossingObject_.EgoStates[5].latPosition = 36.30;
    std::cout << "CrossingObject_.EgoStates[5].latPosition(float32): " << CrossingObject_.EgoStates[5].latPosition << std::endl;
    CrossingObject_.EgoStates[5].longPosition = 37.40;
    std::cout << "CrossingObject_.EgoStates[5].longPosition(float32): " << CrossingObject_.EgoStates[5].longPosition << std::endl;
    CrossingObject_.EgoStates[5].latVelocity = 38.50;
    std::cout << "CrossingObject_.EgoStates[5].latVelocity(float32): " << CrossingObject_.EgoStates[5].latVelocity << std::endl;
    CrossingObject_.EgoStates[5].longVelocity = 39.60;
    std::cout << "CrossingObject_.EgoStates[5].longVelocity(float32): " << CrossingObject_.EgoStates[5].longVelocity << std::endl;
    CrossingObject_.EgoStates[6].latAcceleration = 40.70;
    std::cout << "CrossingObject_.EgoStates[6].latAcceleration(float32): " << CrossingObject_.EgoStates[6].latAcceleration << std::endl;
    CrossingObject_.EgoStates[6].longAcceleration = 41.80;
    std::cout << "CrossingObject_.EgoStates[6].longAcceleration(float32): " << CrossingObject_.EgoStates[6].longAcceleration << std::endl;
    CrossingObject_.EgoStates[6].latPosition = 42.90;
    std::cout << "CrossingObject_.EgoStates[6].latPosition(float32): " << CrossingObject_.EgoStates[6].latPosition << std::endl;
    CrossingObject_.EgoStates[6].longPosition = 44.00;
    std::cout << "CrossingObject_.EgoStates[6].longPosition(float32): " << CrossingObject_.EgoStates[6].longPosition << std::endl;
    CrossingObject_.EgoStates[6].latVelocity = 45.10;
    std::cout << "CrossingObject_.EgoStates[6].latVelocity(float32): " << CrossingObject_.EgoStates[6].latVelocity << std::endl;
    CrossingObject_.EgoStates[6].longVelocity = 46.20;
    std::cout << "CrossingObject_.EgoStates[6].longVelocity(float32): " << CrossingObject_.EgoStates[6].longVelocity << std::endl;
    CrossingObject_.EgoStates[7].latAcceleration = 47.30;
    std::cout << "CrossingObject_.EgoStates[7].latAcceleration(float32): " << CrossingObject_.EgoStates[7].latAcceleration << std::endl;
    CrossingObject_.EgoStates[7].longAcceleration = 48.40;
    std::cout << "CrossingObject_.EgoStates[7].longAcceleration(float32): " << CrossingObject_.EgoStates[7].longAcceleration << std::endl;
    CrossingObject_.EgoStates[7].latPosition = 49.50;
    std::cout << "CrossingObject_.EgoStates[7].latPosition(float32): " << CrossingObject_.EgoStates[7].latPosition << std::endl;
    CrossingObject_.EgoStates[7].longPosition = 50.60;
    std::cout << "CrossingObject_.EgoStates[7].longPosition(float32): " << CrossingObject_.EgoStates[7].longPosition << std::endl;
    CrossingObject_.EgoStates[7].latVelocity = 51.70;
    std::cout << "CrossingObject_.EgoStates[7].latVelocity(float32): " << CrossingObject_.EgoStates[7].latVelocity << std::endl;
    CrossingObject_.EgoStates[7].longVelocity = 52.80;
    std::cout << "CrossingObject_.EgoStates[7].longVelocity(float32): " << CrossingObject_.EgoStates[7].longVelocity << std::endl;
    CrossingObject_.EgoStates[8].latAcceleration = 53.90;
    std::cout << "CrossingObject_.EgoStates[8].latAcceleration(float32): " << CrossingObject_.EgoStates[8].latAcceleration << std::endl;
    CrossingObject_.EgoStates[8].longAcceleration = 55.00;
    std::cout << "CrossingObject_.EgoStates[8].longAcceleration(float32): " << CrossingObject_.EgoStates[8].longAcceleration << std::endl;
    CrossingObject_.EgoStates[8].latPosition = 56.10;
    std::cout << "CrossingObject_.EgoStates[8].latPosition(float32): " << CrossingObject_.EgoStates[8].latPosition << std::endl;
    CrossingObject_.EgoStates[8].longPosition = 57.20;
    std::cout << "CrossingObject_.EgoStates[8].longPosition(float32): " << CrossingObject_.EgoStates[8].longPosition << std::endl;
    CrossingObject_.EgoStates[8].latVelocity = 58.30;
    std::cout << "CrossingObject_.EgoStates[8].latVelocity(float32): " << CrossingObject_.EgoStates[8].latVelocity << std::endl;
    CrossingObject_.EgoStates[8].longVelocity = 59.40;
    std::cout << "CrossingObject_.EgoStates[8].longVelocity(float32): " << CrossingObject_.EgoStates[8].longVelocity << std::endl;
    CrossingObject_.EgoStates[9].latAcceleration = 60.50;
    std::cout << "CrossingObject_.EgoStates[9].latAcceleration(float32): " << CrossingObject_.EgoStates[9].latAcceleration << std::endl;
    CrossingObject_.EgoStates[9].longAcceleration = 61.60;
    std::cout << "CrossingObject_.EgoStates[9].longAcceleration(float32): " << CrossingObject_.EgoStates[9].longAcceleration << std::endl;
    CrossingObject_.EgoStates[9].latPosition = 62.70;
    std::cout << "CrossingObject_.EgoStates[9].latPosition(float32): " << CrossingObject_.EgoStates[9].latPosition << std::endl;
    CrossingObject_.EgoStates[9].longPosition = 63.80;
    std::cout << "CrossingObject_.EgoStates[9].longPosition(float32): " << CrossingObject_.EgoStates[9].longPosition << std::endl;
    CrossingObject_.EgoStates[9].latVelocity = 64.90;
    std::cout << "CrossingObject_.EgoStates[9].latVelocity(float32): " << CrossingObject_.EgoStates[9].latVelocity << std::endl;
    CrossingObject_.EgoStates[9].longVelocity = 66.00;
    std::cout << "CrossingObject_.EgoStates[9].longVelocity(float32): " << CrossingObject_.EgoStates[9].longVelocity << std::endl;
    CrossingObject_.EgoStates[10].latAcceleration = 67.10;
    std::cout << "CrossingObject_.EgoStates[10].latAcceleration(float32): " << CrossingObject_.EgoStates[10].latAcceleration << std::endl;
    CrossingObject_.EgoStates[10].longAcceleration = 68.20;
    std::cout << "CrossingObject_.EgoStates[10].longAcceleration(float32): " << CrossingObject_.EgoStates[10].longAcceleration << std::endl;
    CrossingObject_.EgoStates[10].latPosition = 69.30;
    std::cout << "CrossingObject_.EgoStates[10].latPosition(float32): " << CrossingObject_.EgoStates[10].latPosition << std::endl;
    CrossingObject_.EgoStates[10].longPosition = 70.40;
    std::cout << "CrossingObject_.EgoStates[10].longPosition(float32): " << CrossingObject_.EgoStates[10].longPosition << std::endl;
    CrossingObject_.EgoStates[10].latVelocity = 71.50;
    std::cout << "CrossingObject_.EgoStates[10].latVelocity(float32): " << CrossingObject_.EgoStates[10].latVelocity << std::endl;
    CrossingObject_.EgoStates[10].longVelocity = 72.60;
    std::cout << "CrossingObject_.EgoStates[10].longVelocity(float32): " << CrossingObject_.EgoStates[10].longVelocity << std::endl;
    CrossingObject_.EgoStates[11].latAcceleration = 73.70;
    std::cout << "CrossingObject_.EgoStates[11].latAcceleration(float32): " << CrossingObject_.EgoStates[11].latAcceleration << std::endl;
    CrossingObject_.EgoStates[11].longAcceleration = 74.80;
    std::cout << "CrossingObject_.EgoStates[11].longAcceleration(float32): " << CrossingObject_.EgoStates[11].longAcceleration << std::endl;
    CrossingObject_.EgoStates[11].latPosition = 75.90;
    std::cout << "CrossingObject_.EgoStates[11].latPosition(float32): " << CrossingObject_.EgoStates[11].latPosition << std::endl;
    CrossingObject_.EgoStates[11].longPosition = 77.00;
    std::cout << "CrossingObject_.EgoStates[11].longPosition(float32): " << CrossingObject_.EgoStates[11].longPosition << std::endl;
    CrossingObject_.EgoStates[11].latVelocity = 78.10;
    std::cout << "CrossingObject_.EgoStates[11].latVelocity(float32): " << CrossingObject_.EgoStates[11].latVelocity << std::endl;
    CrossingObject_.EgoStates[11].longVelocity = 79.20;
    std::cout << "CrossingObject_.EgoStates[11].longVelocity(float32): " << CrossingObject_.EgoStates[11].longVelocity << std::endl;
    CrossingObject_.EgoStates[12].latAcceleration = 80.30;
    std::cout << "CrossingObject_.EgoStates[12].latAcceleration(float32): " << CrossingObject_.EgoStates[12].latAcceleration << std::endl;
    CrossingObject_.EgoStates[12].longAcceleration = 81.40;
    std::cout << "CrossingObject_.EgoStates[12].longAcceleration(float32): " << CrossingObject_.EgoStates[12].longAcceleration << std::endl;
    CrossingObject_.EgoStates[12].latPosition = 82.50;
    std::cout << "CrossingObject_.EgoStates[12].latPosition(float32): " << CrossingObject_.EgoStates[12].latPosition << std::endl;
    CrossingObject_.EgoStates[12].longPosition = 83.60;
    std::cout << "CrossingObject_.EgoStates[12].longPosition(float32): " << CrossingObject_.EgoStates[12].longPosition << std::endl;
    CrossingObject_.EgoStates[12].latVelocity = 84.70;
    std::cout << "CrossingObject_.EgoStates[12].latVelocity(float32): " << CrossingObject_.EgoStates[12].latVelocity << std::endl;
    CrossingObject_.EgoStates[12].longVelocity = 85.80;
    std::cout << "CrossingObject_.EgoStates[12].longVelocity(float32): " << CrossingObject_.EgoStates[12].longVelocity << std::endl;
    CrossingObject_.EgoStates[13].latAcceleration = 86.90;
    std::cout << "CrossingObject_.EgoStates[13].latAcceleration(float32): " << CrossingObject_.EgoStates[13].latAcceleration << std::endl;
    CrossingObject_.EgoStates[13].longAcceleration = 88.00;
    std::cout << "CrossingObject_.EgoStates[13].longAcceleration(float32): " << CrossingObject_.EgoStates[13].longAcceleration << std::endl;
    CrossingObject_.EgoStates[13].latPosition = 89.10;
    std::cout << "CrossingObject_.EgoStates[13].latPosition(float32): " << CrossingObject_.EgoStates[13].latPosition << std::endl;
    CrossingObject_.EgoStates[13].longPosition = 90.20;
    std::cout << "CrossingObject_.EgoStates[13].longPosition(float32): " << CrossingObject_.EgoStates[13].longPosition << std::endl;
    CrossingObject_.EgoStates[13].latVelocity = 91.30;
    std::cout << "CrossingObject_.EgoStates[13].latVelocity(float32): " << CrossingObject_.EgoStates[13].latVelocity << std::endl;
    CrossingObject_.EgoStates[13].longVelocity = 92.40;
    std::cout << "CrossingObject_.EgoStates[13].longVelocity(float32): " << CrossingObject_.EgoStates[13].longVelocity << std::endl;
    CrossingObject_.EgoStates[14].latAcceleration = 93.50;
    std::cout << "CrossingObject_.EgoStates[14].latAcceleration(float32): " << CrossingObject_.EgoStates[14].latAcceleration << std::endl;
    CrossingObject_.EgoStates[14].longAcceleration = 94.60;
    std::cout << "CrossingObject_.EgoStates[14].longAcceleration(float32): " << CrossingObject_.EgoStates[14].longAcceleration << std::endl;
    CrossingObject_.EgoStates[14].latPosition = 95.70;
    std::cout << "CrossingObject_.EgoStates[14].latPosition(float32): " << CrossingObject_.EgoStates[14].latPosition << std::endl;
    CrossingObject_.EgoStates[14].longPosition = 96.80;
    std::cout << "CrossingObject_.EgoStates[14].longPosition(float32): " << CrossingObject_.EgoStates[14].longPosition << std::endl;
    CrossingObject_.EgoStates[14].latVelocity = 97.90;
    std::cout << "CrossingObject_.EgoStates[14].latVelocity(float32): " << CrossingObject_.EgoStates[14].latVelocity << std::endl;
    CrossingObject_.EgoStates[14].longVelocity = 99.00;
    std::cout << "CrossingObject_.EgoStates[14].longVelocity(float32): " << CrossingObject_.EgoStates[14].longVelocity << std::endl;
    CrossingObject_.EgoStates[15].latAcceleration = 100.10;
    std::cout << "CrossingObject_.EgoStates[15].latAcceleration(float32): " << CrossingObject_.EgoStates[15].latAcceleration << std::endl;
    CrossingObject_.EgoStates[15].longAcceleration = 101.20;
    std::cout << "CrossingObject_.EgoStates[15].longAcceleration(float32): " << CrossingObject_.EgoStates[15].longAcceleration << std::endl;
    CrossingObject_.EgoStates[15].latPosition = 102.30;
    std::cout << "CrossingObject_.EgoStates[15].latPosition(float32): " << CrossingObject_.EgoStates[15].latPosition << std::endl;
    CrossingObject_.EgoStates[15].longPosition = 103.40;
    std::cout << "CrossingObject_.EgoStates[15].longPosition(float32): " << CrossingObject_.EgoStates[15].longPosition << std::endl;
    CrossingObject_.EgoStates[15].latVelocity = 104.50;
    std::cout << "CrossingObject_.EgoStates[15].latVelocity(float32): " << CrossingObject_.EgoStates[15].latVelocity << std::endl;
    CrossingObject_.EgoStates[15].longVelocity = 105.60;
    std::cout << "CrossingObject_.EgoStates[15].longVelocity(float32): " << CrossingObject_.EgoStates[15].longVelocity << std::endl;
    CrossingObject_.EgoStates[16].latAcceleration = 106.70;
    std::cout << "CrossingObject_.EgoStates[16].latAcceleration(float32): " << CrossingObject_.EgoStates[16].latAcceleration << std::endl;
    CrossingObject_.EgoStates[16].longAcceleration = 107.80;
    std::cout << "CrossingObject_.EgoStates[16].longAcceleration(float32): " << CrossingObject_.EgoStates[16].longAcceleration << std::endl;
    CrossingObject_.EgoStates[16].latPosition = 108.90;
    std::cout << "CrossingObject_.EgoStates[16].latPosition(float32): " << CrossingObject_.EgoStates[16].latPosition << std::endl;
    CrossingObject_.EgoStates[16].longPosition = 110.00;
    std::cout << "CrossingObject_.EgoStates[16].longPosition(float32): " << CrossingObject_.EgoStates[16].longPosition << std::endl;
    CrossingObject_.EgoStates[16].latVelocity = 111.10;
    std::cout << "CrossingObject_.EgoStates[16].latVelocity(float32): " << CrossingObject_.EgoStates[16].latVelocity << std::endl;
    CrossingObject_.EgoStates[16].longVelocity = 112.20;
    std::cout << "CrossingObject_.EgoStates[16].longVelocity(float32): " << CrossingObject_.EgoStates[16].longVelocity << std::endl;
    CrossingObject_.EgoStates[17].latAcceleration = 113.30;
    std::cout << "CrossingObject_.EgoStates[17].latAcceleration(float32): " << CrossingObject_.EgoStates[17].latAcceleration << std::endl;
    CrossingObject_.EgoStates[17].longAcceleration = 114.40;
    std::cout << "CrossingObject_.EgoStates[17].longAcceleration(float32): " << CrossingObject_.EgoStates[17].longAcceleration << std::endl;
    CrossingObject_.EgoStates[17].latPosition = 115.50;
    std::cout << "CrossingObject_.EgoStates[17].latPosition(float32): " << CrossingObject_.EgoStates[17].latPosition << std::endl;
    CrossingObject_.EgoStates[17].longPosition = 116.60;
    std::cout << "CrossingObject_.EgoStates[17].longPosition(float32): " << CrossingObject_.EgoStates[17].longPosition << std::endl;
    CrossingObject_.EgoStates[17].latVelocity = 117.70;
    std::cout << "CrossingObject_.EgoStates[17].latVelocity(float32): " << CrossingObject_.EgoStates[17].latVelocity << std::endl;
    CrossingObject_.EgoStates[17].longVelocity = 118.80;
    std::cout << "CrossingObject_.EgoStates[17].longVelocity(float32): " << CrossingObject_.EgoStates[17].longVelocity << std::endl;
    CrossingObject_.EgoStates[18].latAcceleration = 119.90;
    std::cout << "CrossingObject_.EgoStates[18].latAcceleration(float32): " << CrossingObject_.EgoStates[18].latAcceleration << std::endl;
    CrossingObject_.EgoStates[18].longAcceleration = 121.00;
    std::cout << "CrossingObject_.EgoStates[18].longAcceleration(float32): " << CrossingObject_.EgoStates[18].longAcceleration << std::endl;
    CrossingObject_.EgoStates[18].latPosition = 122.10;
    std::cout << "CrossingObject_.EgoStates[18].latPosition(float32): " << CrossingObject_.EgoStates[18].latPosition << std::endl;
    CrossingObject_.EgoStates[18].longPosition = 123.20;
    std::cout << "CrossingObject_.EgoStates[18].longPosition(float32): " << CrossingObject_.EgoStates[18].longPosition << std::endl;
    CrossingObject_.EgoStates[18].latVelocity = 124.30;
    std::cout << "CrossingObject_.EgoStates[18].latVelocity(float32): " << CrossingObject_.EgoStates[18].latVelocity << std::endl;
    CrossingObject_.EgoStates[18].longVelocity = 125.40;
    std::cout << "CrossingObject_.EgoStates[18].longVelocity(float32): " << CrossingObject_.EgoStates[18].longVelocity << std::endl;
    CrossingObject_.EgoStates[19].latAcceleration = 126.50;
    std::cout << "CrossingObject_.EgoStates[19].latAcceleration(float32): " << CrossingObject_.EgoStates[19].latAcceleration << std::endl;
    CrossingObject_.EgoStates[19].longAcceleration = 127.60;
    std::cout << "CrossingObject_.EgoStates[19].longAcceleration(float32): " << CrossingObject_.EgoStates[19].longAcceleration << std::endl;
    CrossingObject_.EgoStates[19].latPosition = 128.70;
    std::cout << "CrossingObject_.EgoStates[19].latPosition(float32): " << CrossingObject_.EgoStates[19].latPosition << std::endl;
    CrossingObject_.EgoStates[19].longPosition = 129.80;
    std::cout << "CrossingObject_.EgoStates[19].longPosition(float32): " << CrossingObject_.EgoStates[19].longPosition << std::endl;
    CrossingObject_.EgoStates[19].latVelocity = 130.90;
    std::cout << "CrossingObject_.EgoStates[19].latVelocity(float32): " << CrossingObject_.EgoStates[19].latVelocity << std::endl;
    CrossingObject_.EgoStates[19].longVelocity = 132.00;
    std::cout << "CrossingObject_.EgoStates[19].longVelocity(float32): " << CrossingObject_.EgoStates[19].longVelocity << std::endl;
    CrossingObject_.EgoStates[20].latAcceleration = 133.10;
    std::cout << "CrossingObject_.EgoStates[20].latAcceleration(float32): " << CrossingObject_.EgoStates[20].latAcceleration << std::endl;
    CrossingObject_.EgoStates[20].longAcceleration = 134.20;
    std::cout << "CrossingObject_.EgoStates[20].longAcceleration(float32): " << CrossingObject_.EgoStates[20].longAcceleration << std::endl;
    CrossingObject_.EgoStates[20].latPosition = 135.30;
    std::cout << "CrossingObject_.EgoStates[20].latPosition(float32): " << CrossingObject_.EgoStates[20].latPosition << std::endl;
    CrossingObject_.EgoStates[20].longPosition = 136.40;
    std::cout << "CrossingObject_.EgoStates[20].longPosition(float32): " << CrossingObject_.EgoStates[20].longPosition << std::endl;
    CrossingObject_.EgoStates[20].latVelocity = 137.50;
    std::cout << "CrossingObject_.EgoStates[20].latVelocity(float32): " << CrossingObject_.EgoStates[20].latVelocity << std::endl;
    CrossingObject_.EgoStates[20].longVelocity = 138.60;
    std::cout << "CrossingObject_.EgoStates[20].longVelocity(float32): " << CrossingObject_.EgoStates[20].longVelocity << std::endl;
    CrossingObject_.EgoStates[21].latAcceleration = 139.70;
    std::cout << "CrossingObject_.EgoStates[21].latAcceleration(float32): " << CrossingObject_.EgoStates[21].latAcceleration << std::endl;
    CrossingObject_.EgoStates[21].longAcceleration = 140.80;
    std::cout << "CrossingObject_.EgoStates[21].longAcceleration(float32): " << CrossingObject_.EgoStates[21].longAcceleration << std::endl;
    CrossingObject_.EgoStates[21].latPosition = 141.90;
    std::cout << "CrossingObject_.EgoStates[21].latPosition(float32): " << CrossingObject_.EgoStates[21].latPosition << std::endl;
    CrossingObject_.EgoStates[21].longPosition = 143.00;
    std::cout << "CrossingObject_.EgoStates[21].longPosition(float32): " << CrossingObject_.EgoStates[21].longPosition << std::endl;
    CrossingObject_.EgoStates[21].latVelocity = 144.10;
    std::cout << "CrossingObject_.EgoStates[21].latVelocity(float32): " << CrossingObject_.EgoStates[21].latVelocity << std::endl;
    CrossingObject_.EgoStates[21].longVelocity = 145.20;
    std::cout << "CrossingObject_.EgoStates[21].longVelocity(float32): " << CrossingObject_.EgoStates[21].longVelocity << std::endl;
    CrossingObject_.EgoStates[22].latAcceleration = 146.30;
    std::cout << "CrossingObject_.EgoStates[22].latAcceleration(float32): " << CrossingObject_.EgoStates[22].latAcceleration << std::endl;
    CrossingObject_.EgoStates[22].longAcceleration = 147.40;
    std::cout << "CrossingObject_.EgoStates[22].longAcceleration(float32): " << CrossingObject_.EgoStates[22].longAcceleration << std::endl;
    CrossingObject_.EgoStates[22].latPosition = 148.50;
    std::cout << "CrossingObject_.EgoStates[22].latPosition(float32): " << CrossingObject_.EgoStates[22].latPosition << std::endl;
    CrossingObject_.EgoStates[22].longPosition = 149.60;
    std::cout << "CrossingObject_.EgoStates[22].longPosition(float32): " << CrossingObject_.EgoStates[22].longPosition << std::endl;
    CrossingObject_.EgoStates[22].latVelocity = 150.70;
    std::cout << "CrossingObject_.EgoStates[22].latVelocity(float32): " << CrossingObject_.EgoStates[22].latVelocity << std::endl;
    CrossingObject_.EgoStates[22].longVelocity = 151.80;
    std::cout << "CrossingObject_.EgoStates[22].longVelocity(float32): " << CrossingObject_.EgoStates[22].longVelocity << std::endl;
    CrossingObject_.EgoStates[23].latAcceleration = 152.90;
    std::cout << "CrossingObject_.EgoStates[23].latAcceleration(float32): " << CrossingObject_.EgoStates[23].latAcceleration << std::endl;
    CrossingObject_.EgoStates[23].longAcceleration = 154.00;
    std::cout << "CrossingObject_.EgoStates[23].longAcceleration(float32): " << CrossingObject_.EgoStates[23].longAcceleration << std::endl;
    CrossingObject_.EgoStates[23].latPosition = 155.10;
    std::cout << "CrossingObject_.EgoStates[23].latPosition(float32): " << CrossingObject_.EgoStates[23].latPosition << std::endl;
    CrossingObject_.EgoStates[23].longPosition = 156.20;
    std::cout << "CrossingObject_.EgoStates[23].longPosition(float32): " << CrossingObject_.EgoStates[23].longPosition << std::endl;
    CrossingObject_.EgoStates[23].latVelocity = 157.30;
    std::cout << "CrossingObject_.EgoStates[23].latVelocity(float32): " << CrossingObject_.EgoStates[23].latVelocity << std::endl;
    CrossingObject_.EgoStates[23].longVelocity = 158.40;
    std::cout << "CrossingObject_.EgoStates[23].longVelocity(float32): " << CrossingObject_.EgoStates[23].longVelocity << std::endl;
    CrossingObject_.EgoStates[24].latAcceleration = 159.50;
    std::cout << "CrossingObject_.EgoStates[24].latAcceleration(float32): " << CrossingObject_.EgoStates[24].latAcceleration << std::endl;
    CrossingObject_.EgoStates[24].longAcceleration = 160.60;
    std::cout << "CrossingObject_.EgoStates[24].longAcceleration(float32): " << CrossingObject_.EgoStates[24].longAcceleration << std::endl;
    CrossingObject_.EgoStates[24].latPosition = 161.70;
    std::cout << "CrossingObject_.EgoStates[24].latPosition(float32): " << CrossingObject_.EgoStates[24].latPosition << std::endl;
    CrossingObject_.EgoStates[24].longPosition = 162.80;
    std::cout << "CrossingObject_.EgoStates[24].longPosition(float32): " << CrossingObject_.EgoStates[24].longPosition << std::endl;
    CrossingObject_.EgoStates[24].latVelocity = 163.90;
    std::cout << "CrossingObject_.EgoStates[24].latVelocity(float32): " << CrossingObject_.EgoStates[24].latVelocity << std::endl;
    CrossingObject_.EgoStates[24].longVelocity = 165.00;
    std::cout << "CrossingObject_.EgoStates[24].longVelocity(float32): " << CrossingObject_.EgoStates[24].longVelocity << std::endl;
    CrossingObject_.EgoStates[25].latAcceleration = 166.10;
    std::cout << "CrossingObject_.EgoStates[25].latAcceleration(float32): " << CrossingObject_.EgoStates[25].latAcceleration << std::endl;
    CrossingObject_.EgoStates[25].longAcceleration = 167.20;
    std::cout << "CrossingObject_.EgoStates[25].longAcceleration(float32): " << CrossingObject_.EgoStates[25].longAcceleration << std::endl;
    CrossingObject_.EgoStates[25].latPosition = 168.30;
    std::cout << "CrossingObject_.EgoStates[25].latPosition(float32): " << CrossingObject_.EgoStates[25].latPosition << std::endl;
    CrossingObject_.EgoStates[25].longPosition = 169.40;
    std::cout << "CrossingObject_.EgoStates[25].longPosition(float32): " << CrossingObject_.EgoStates[25].longPosition << std::endl;
    CrossingObject_.EgoStates[25].latVelocity = 170.50;
    std::cout << "CrossingObject_.EgoStates[25].latVelocity(float32): " << CrossingObject_.EgoStates[25].latVelocity << std::endl;
    CrossingObject_.EgoStates[25].longVelocity = 171.60;
    std::cout << "CrossingObject_.EgoStates[25].longVelocity(float32): " << CrossingObject_.EgoStates[25].longVelocity << std::endl;
    CrossingObject_.EgoStates[26].latAcceleration = 172.70;
    std::cout << "CrossingObject_.EgoStates[26].latAcceleration(float32): " << CrossingObject_.EgoStates[26].latAcceleration << std::endl;
    CrossingObject_.EgoStates[26].longAcceleration = 173.80;
    std::cout << "CrossingObject_.EgoStates[26].longAcceleration(float32): " << CrossingObject_.EgoStates[26].longAcceleration << std::endl;
    CrossingObject_.EgoStates[26].latPosition = 174.90;
    std::cout << "CrossingObject_.EgoStates[26].latPosition(float32): " << CrossingObject_.EgoStates[26].latPosition << std::endl;
    CrossingObject_.EgoStates[26].longPosition = 176.00;
    std::cout << "CrossingObject_.EgoStates[26].longPosition(float32): " << CrossingObject_.EgoStates[26].longPosition << std::endl;
    CrossingObject_.EgoStates[26].latVelocity = 177.10;
    std::cout << "CrossingObject_.EgoStates[26].latVelocity(float32): " << CrossingObject_.EgoStates[26].latVelocity << std::endl;
    CrossingObject_.EgoStates[26].longVelocity = 178.20;
    std::cout << "CrossingObject_.EgoStates[26].longVelocity(float32): " << CrossingObject_.EgoStates[26].longVelocity << std::endl;
    CrossingObject_.EgoStates[27].latAcceleration = 179.30;
    std::cout << "CrossingObject_.EgoStates[27].latAcceleration(float32): " << CrossingObject_.EgoStates[27].latAcceleration << std::endl;
    CrossingObject_.EgoStates[27].longAcceleration = 180.40;
    std::cout << "CrossingObject_.EgoStates[27].longAcceleration(float32): " << CrossingObject_.EgoStates[27].longAcceleration << std::endl;
    CrossingObject_.EgoStates[27].latPosition = 181.50;
    std::cout << "CrossingObject_.EgoStates[27].latPosition(float32): " << CrossingObject_.EgoStates[27].latPosition << std::endl;
    CrossingObject_.EgoStates[27].longPosition = 182.60;
    std::cout << "CrossingObject_.EgoStates[27].longPosition(float32): " << CrossingObject_.EgoStates[27].longPosition << std::endl;
    CrossingObject_.EgoStates[27].latVelocity = 183.70;
    std::cout << "CrossingObject_.EgoStates[27].latVelocity(float32): " << CrossingObject_.EgoStates[27].latVelocity << std::endl;
    CrossingObject_.EgoStates[27].longVelocity = 184.80;
    std::cout << "CrossingObject_.EgoStates[27].longVelocity(float32): " << CrossingObject_.EgoStates[27].longVelocity << std::endl;
    CrossingObject_.EgoStates[28].latAcceleration = 185.90;
    std::cout << "CrossingObject_.EgoStates[28].latAcceleration(float32): " << CrossingObject_.EgoStates[28].latAcceleration << std::endl;
    CrossingObject_.EgoStates[28].longAcceleration = 187.00;
    std::cout << "CrossingObject_.EgoStates[28].longAcceleration(float32): " << CrossingObject_.EgoStates[28].longAcceleration << std::endl;
    CrossingObject_.EgoStates[28].latPosition = 188.10;
    std::cout << "CrossingObject_.EgoStates[28].latPosition(float32): " << CrossingObject_.EgoStates[28].latPosition << std::endl;
    CrossingObject_.EgoStates[28].longPosition = 189.20;
    std::cout << "CrossingObject_.EgoStates[28].longPosition(float32): " << CrossingObject_.EgoStates[28].longPosition << std::endl;
    CrossingObject_.EgoStates[28].latVelocity = 190.30;
    std::cout << "CrossingObject_.EgoStates[28].latVelocity(float32): " << CrossingObject_.EgoStates[28].latVelocity << std::endl;
    CrossingObject_.EgoStates[28].longVelocity = 191.40;
    std::cout << "CrossingObject_.EgoStates[28].longVelocity(float32): " << CrossingObject_.EgoStates[28].longVelocity << std::endl;
    CrossingObject_.EgoStates[29].latAcceleration = 192.50;
    std::cout << "CrossingObject_.EgoStates[29].latAcceleration(float32): " << CrossingObject_.EgoStates[29].latAcceleration << std::endl;
    CrossingObject_.EgoStates[29].longAcceleration = 193.60;
    std::cout << "CrossingObject_.EgoStates[29].longAcceleration(float32): " << CrossingObject_.EgoStates[29].longAcceleration << std::endl;
    CrossingObject_.EgoStates[29].latPosition = 194.70;
    std::cout << "CrossingObject_.EgoStates[29].latPosition(float32): " << CrossingObject_.EgoStates[29].latPosition << std::endl;
    CrossingObject_.EgoStates[29].longPosition = 195.80;
    std::cout << "CrossingObject_.EgoStates[29].longPosition(float32): " << CrossingObject_.EgoStates[29].longPosition << std::endl;
    CrossingObject_.EgoStates[29].latVelocity = 196.90;
    std::cout << "CrossingObject_.EgoStates[29].latVelocity(float32): " << CrossingObject_.EgoStates[29].latVelocity << std::endl;
    CrossingObject_.EgoStates[29].longVelocity = 198.00;
    std::cout << "CrossingObject_.EgoStates[29].longVelocity(float32): " << CrossingObject_.EgoStates[29].longVelocity << std::endl;
    CrossingObject_.Properties[0].id = 1;
    std::cout << "CrossingObject_.Properties[0].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[0].id) << std::dec  << std::endl;
    CrossingObject_.Properties[0].motionPattern = 1;
    std::cout << "CrossingObject_.Properties[0].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[0].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[0].referencePoint = 2;
    std::cout << "CrossingObject_.Properties[0].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[0].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[0].type = 3;
    std::cout << "CrossingObject_.Properties[0].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[0].type) << std::dec  << std::endl;
    CrossingObject_.Properties[0].width = 199.10;
    std::cout << "CrossingObject_.Properties[0].width(float32): " << CrossingObject_.Properties[0].width << std::endl;
    CrossingObject_.Properties[0].length = 200.20;
    std::cout << "CrossingObject_.Properties[0].length(float32): " << CrossingObject_.Properties[0].length << std::endl;
    CrossingObject_.Properties[0].cmbbQly = 4;
    std::cout << "CrossingObject_.Properties[0].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[0].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[1].id = 2;
    std::cout << "CrossingObject_.Properties[1].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[1].id) << std::dec  << std::endl;
    CrossingObject_.Properties[1].motionPattern = 5;
    std::cout << "CrossingObject_.Properties[1].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[1].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[1].referencePoint = 6;
    std::cout << "CrossingObject_.Properties[1].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[1].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[1].type = 7;
    std::cout << "CrossingObject_.Properties[1].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[1].type) << std::dec  << std::endl;
    CrossingObject_.Properties[1].width = 201.30;
    std::cout << "CrossingObject_.Properties[1].width(float32): " << CrossingObject_.Properties[1].width << std::endl;
    CrossingObject_.Properties[1].length = 202.40;
    std::cout << "CrossingObject_.Properties[1].length(float32): " << CrossingObject_.Properties[1].length << std::endl;
    CrossingObject_.Properties[1].cmbbQly = 8;
    std::cout << "CrossingObject_.Properties[1].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[1].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[2].id = 3;
    std::cout << "CrossingObject_.Properties[2].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[2].id) << std::dec  << std::endl;
    CrossingObject_.Properties[2].motionPattern = 9;
    std::cout << "CrossingObject_.Properties[2].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[2].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[2].referencePoint = 10;
    std::cout << "CrossingObject_.Properties[2].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[2].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[2].type = 11;
    std::cout << "CrossingObject_.Properties[2].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[2].type) << std::dec  << std::endl;
    CrossingObject_.Properties[2].width = 203.50;
    std::cout << "CrossingObject_.Properties[2].width(float32): " << CrossingObject_.Properties[2].width << std::endl;
    CrossingObject_.Properties[2].length = 204.60;
    std::cout << "CrossingObject_.Properties[2].length(float32): " << CrossingObject_.Properties[2].length << std::endl;
    CrossingObject_.Properties[2].cmbbQly = 12;
    std::cout << "CrossingObject_.Properties[2].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[2].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[3].id = 4;
    std::cout << "CrossingObject_.Properties[3].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[3].id) << std::dec  << std::endl;
    CrossingObject_.Properties[3].motionPattern = 13;
    std::cout << "CrossingObject_.Properties[3].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[3].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[3].referencePoint = 14;
    std::cout << "CrossingObject_.Properties[3].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[3].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[3].type = 15;
    std::cout << "CrossingObject_.Properties[3].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[3].type) << std::dec  << std::endl;
    CrossingObject_.Properties[3].width = 205.70;
    std::cout << "CrossingObject_.Properties[3].width(float32): " << CrossingObject_.Properties[3].width << std::endl;
    CrossingObject_.Properties[3].length = 206.80;
    std::cout << "CrossingObject_.Properties[3].length(float32): " << CrossingObject_.Properties[3].length << std::endl;
    CrossingObject_.Properties[3].cmbbQly = 16;
    std::cout << "CrossingObject_.Properties[3].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[3].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[4].id = 5;
    std::cout << "CrossingObject_.Properties[4].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[4].id) << std::dec  << std::endl;
    CrossingObject_.Properties[4].motionPattern = 17;
    std::cout << "CrossingObject_.Properties[4].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[4].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[4].referencePoint = 18;
    std::cout << "CrossingObject_.Properties[4].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[4].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[4].type = 19;
    std::cout << "CrossingObject_.Properties[4].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[4].type) << std::dec  << std::endl;
    CrossingObject_.Properties[4].width = 207.90;
    std::cout << "CrossingObject_.Properties[4].width(float32): " << CrossingObject_.Properties[4].width << std::endl;
    CrossingObject_.Properties[4].length = 209.00;
    std::cout << "CrossingObject_.Properties[4].length(float32): " << CrossingObject_.Properties[4].length << std::endl;
    CrossingObject_.Properties[4].cmbbQly = 20;
    std::cout << "CrossingObject_.Properties[4].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[4].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[5].id = 6;
    std::cout << "CrossingObject_.Properties[5].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[5].id) << std::dec  << std::endl;
    CrossingObject_.Properties[5].motionPattern = 21;
    std::cout << "CrossingObject_.Properties[5].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[5].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[5].referencePoint = 22;
    std::cout << "CrossingObject_.Properties[5].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[5].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[5].type = 23;
    std::cout << "CrossingObject_.Properties[5].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[5].type) << std::dec  << std::endl;
    CrossingObject_.Properties[5].width = 210.10;
    std::cout << "CrossingObject_.Properties[5].width(float32): " << CrossingObject_.Properties[5].width << std::endl;
    CrossingObject_.Properties[5].length = 211.20;
    std::cout << "CrossingObject_.Properties[5].length(float32): " << CrossingObject_.Properties[5].length << std::endl;
    CrossingObject_.Properties[5].cmbbQly = 24;
    std::cout << "CrossingObject_.Properties[5].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[5].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[6].id = 7;
    std::cout << "CrossingObject_.Properties[6].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[6].id) << std::dec  << std::endl;
    CrossingObject_.Properties[6].motionPattern = 25;
    std::cout << "CrossingObject_.Properties[6].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[6].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[6].referencePoint = 26;
    std::cout << "CrossingObject_.Properties[6].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[6].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[6].type = 27;
    std::cout << "CrossingObject_.Properties[6].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[6].type) << std::dec  << std::endl;
    CrossingObject_.Properties[6].width = 212.30;
    std::cout << "CrossingObject_.Properties[6].width(float32): " << CrossingObject_.Properties[6].width << std::endl;
    CrossingObject_.Properties[6].length = 213.40;
    std::cout << "CrossingObject_.Properties[6].length(float32): " << CrossingObject_.Properties[6].length << std::endl;
    CrossingObject_.Properties[6].cmbbQly = 28;
    std::cout << "CrossingObject_.Properties[6].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[6].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[7].id = 8;
    std::cout << "CrossingObject_.Properties[7].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[7].id) << std::dec  << std::endl;
    CrossingObject_.Properties[7].motionPattern = 29;
    std::cout << "CrossingObject_.Properties[7].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[7].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[7].referencePoint = 30;
    std::cout << "CrossingObject_.Properties[7].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[7].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[7].type = 31;
    std::cout << "CrossingObject_.Properties[7].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[7].type) << std::dec  << std::endl;
    CrossingObject_.Properties[7].width = 214.50;
    std::cout << "CrossingObject_.Properties[7].width(float32): " << CrossingObject_.Properties[7].width << std::endl;
    CrossingObject_.Properties[7].length = 215.60;
    std::cout << "CrossingObject_.Properties[7].length(float32): " << CrossingObject_.Properties[7].length << std::endl;
    CrossingObject_.Properties[7].cmbbQly = 32;
    std::cout << "CrossingObject_.Properties[7].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[7].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[8].id = 9;
    std::cout << "CrossingObject_.Properties[8].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[8].id) << std::dec  << std::endl;
    CrossingObject_.Properties[8].motionPattern = 33;
    std::cout << "CrossingObject_.Properties[8].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[8].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[8].referencePoint = 34;
    std::cout << "CrossingObject_.Properties[8].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[8].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[8].type = 35;
    std::cout << "CrossingObject_.Properties[8].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[8].type) << std::dec  << std::endl;
    CrossingObject_.Properties[8].width = 216.70;
    std::cout << "CrossingObject_.Properties[8].width(float32): " << CrossingObject_.Properties[8].width << std::endl;
    CrossingObject_.Properties[8].length = 217.80;
    std::cout << "CrossingObject_.Properties[8].length(float32): " << CrossingObject_.Properties[8].length << std::endl;
    CrossingObject_.Properties[8].cmbbQly = 36;
    std::cout << "CrossingObject_.Properties[8].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[8].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[9].id = 10;
    std::cout << "CrossingObject_.Properties[9].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[9].id) << std::dec  << std::endl;
    CrossingObject_.Properties[9].motionPattern = 37;
    std::cout << "CrossingObject_.Properties[9].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[9].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[9].referencePoint = 38;
    std::cout << "CrossingObject_.Properties[9].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[9].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[9].type = 39;
    std::cout << "CrossingObject_.Properties[9].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[9].type) << std::dec  << std::endl;
    CrossingObject_.Properties[9].width = 218.90;
    std::cout << "CrossingObject_.Properties[9].width(float32): " << CrossingObject_.Properties[9].width << std::endl;
    CrossingObject_.Properties[9].length = 220.00;
    std::cout << "CrossingObject_.Properties[9].length(float32): " << CrossingObject_.Properties[9].length << std::endl;
    CrossingObject_.Properties[9].cmbbQly = 40;
    std::cout << "CrossingObject_.Properties[9].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[9].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[10].id = 11;
    std::cout << "CrossingObject_.Properties[10].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[10].id) << std::dec  << std::endl;
    CrossingObject_.Properties[10].motionPattern = 41;
    std::cout << "CrossingObject_.Properties[10].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[10].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[10].referencePoint = 42;
    std::cout << "CrossingObject_.Properties[10].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[10].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[10].type = 43;
    std::cout << "CrossingObject_.Properties[10].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[10].type) << std::dec  << std::endl;
    CrossingObject_.Properties[10].width = 221.10;
    std::cout << "CrossingObject_.Properties[10].width(float32): " << CrossingObject_.Properties[10].width << std::endl;
    CrossingObject_.Properties[10].length = 222.20;
    std::cout << "CrossingObject_.Properties[10].length(float32): " << CrossingObject_.Properties[10].length << std::endl;
    CrossingObject_.Properties[10].cmbbQly = 44;
    std::cout << "CrossingObject_.Properties[10].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[10].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[11].id = 12;
    std::cout << "CrossingObject_.Properties[11].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[11].id) << std::dec  << std::endl;
    CrossingObject_.Properties[11].motionPattern = 45;
    std::cout << "CrossingObject_.Properties[11].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[11].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[11].referencePoint = 46;
    std::cout << "CrossingObject_.Properties[11].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[11].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[11].type = 47;
    std::cout << "CrossingObject_.Properties[11].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[11].type) << std::dec  << std::endl;
    CrossingObject_.Properties[11].width = 223.30;
    std::cout << "CrossingObject_.Properties[11].width(float32): " << CrossingObject_.Properties[11].width << std::endl;
    CrossingObject_.Properties[11].length = 224.40;
    std::cout << "CrossingObject_.Properties[11].length(float32): " << CrossingObject_.Properties[11].length << std::endl;
    CrossingObject_.Properties[11].cmbbQly = 48;
    std::cout << "CrossingObject_.Properties[11].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[11].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[12].id = 13;
    std::cout << "CrossingObject_.Properties[12].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[12].id) << std::dec  << std::endl;
    CrossingObject_.Properties[12].motionPattern = 49;
    std::cout << "CrossingObject_.Properties[12].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[12].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[12].referencePoint = 50;
    std::cout << "CrossingObject_.Properties[12].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[12].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[12].type = 51;
    std::cout << "CrossingObject_.Properties[12].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[12].type) << std::dec  << std::endl;
    CrossingObject_.Properties[12].width = 225.50;
    std::cout << "CrossingObject_.Properties[12].width(float32): " << CrossingObject_.Properties[12].width << std::endl;
    CrossingObject_.Properties[12].length = 226.60;
    std::cout << "CrossingObject_.Properties[12].length(float32): " << CrossingObject_.Properties[12].length << std::endl;
    CrossingObject_.Properties[12].cmbbQly = 52;
    std::cout << "CrossingObject_.Properties[12].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[12].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[13].id = 14;
    std::cout << "CrossingObject_.Properties[13].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[13].id) << std::dec  << std::endl;
    CrossingObject_.Properties[13].motionPattern = 53;
    std::cout << "CrossingObject_.Properties[13].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[13].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[13].referencePoint = 54;
    std::cout << "CrossingObject_.Properties[13].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[13].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[13].type = 55;
    std::cout << "CrossingObject_.Properties[13].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[13].type) << std::dec  << std::endl;
    CrossingObject_.Properties[13].width = 227.70;
    std::cout << "CrossingObject_.Properties[13].width(float32): " << CrossingObject_.Properties[13].width << std::endl;
    CrossingObject_.Properties[13].length = 228.80;
    std::cout << "CrossingObject_.Properties[13].length(float32): " << CrossingObject_.Properties[13].length << std::endl;
    CrossingObject_.Properties[13].cmbbQly = 56;
    std::cout << "CrossingObject_.Properties[13].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[13].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[14].id = 15;
    std::cout << "CrossingObject_.Properties[14].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[14].id) << std::dec  << std::endl;
    CrossingObject_.Properties[14].motionPattern = 57;
    std::cout << "CrossingObject_.Properties[14].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[14].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[14].referencePoint = 58;
    std::cout << "CrossingObject_.Properties[14].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[14].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[14].type = 59;
    std::cout << "CrossingObject_.Properties[14].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[14].type) << std::dec  << std::endl;
    CrossingObject_.Properties[14].width = 229.90;
    std::cout << "CrossingObject_.Properties[14].width(float32): " << CrossingObject_.Properties[14].width << std::endl;
    CrossingObject_.Properties[14].length = 231.00;
    std::cout << "CrossingObject_.Properties[14].length(float32): " << CrossingObject_.Properties[14].length << std::endl;
    CrossingObject_.Properties[14].cmbbQly = 60;
    std::cout << "CrossingObject_.Properties[14].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[14].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[15].id = 16;
    std::cout << "CrossingObject_.Properties[15].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[15].id) << std::dec  << std::endl;
    CrossingObject_.Properties[15].motionPattern = 61;
    std::cout << "CrossingObject_.Properties[15].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[15].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[15].referencePoint = 62;
    std::cout << "CrossingObject_.Properties[15].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[15].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[15].type = 63;
    std::cout << "CrossingObject_.Properties[15].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[15].type) << std::dec  << std::endl;
    CrossingObject_.Properties[15].width = 232.10;
    std::cout << "CrossingObject_.Properties[15].width(float32): " << CrossingObject_.Properties[15].width << std::endl;
    CrossingObject_.Properties[15].length = 233.20;
    std::cout << "CrossingObject_.Properties[15].length(float32): " << CrossingObject_.Properties[15].length << std::endl;
    CrossingObject_.Properties[15].cmbbQly = 64;
    std::cout << "CrossingObject_.Properties[15].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[15].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[16].id = 17;
    std::cout << "CrossingObject_.Properties[16].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[16].id) << std::dec  << std::endl;
    CrossingObject_.Properties[16].motionPattern = 65;
    std::cout << "CrossingObject_.Properties[16].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[16].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[16].referencePoint = 66;
    std::cout << "CrossingObject_.Properties[16].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[16].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[16].type = 67;
    std::cout << "CrossingObject_.Properties[16].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[16].type) << std::dec  << std::endl;
    CrossingObject_.Properties[16].width = 234.30;
    std::cout << "CrossingObject_.Properties[16].width(float32): " << CrossingObject_.Properties[16].width << std::endl;
    CrossingObject_.Properties[16].length = 235.40;
    std::cout << "CrossingObject_.Properties[16].length(float32): " << CrossingObject_.Properties[16].length << std::endl;
    CrossingObject_.Properties[16].cmbbQly = 68;
    std::cout << "CrossingObject_.Properties[16].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[16].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[17].id = 18;
    std::cout << "CrossingObject_.Properties[17].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[17].id) << std::dec  << std::endl;
    CrossingObject_.Properties[17].motionPattern = 69;
    std::cout << "CrossingObject_.Properties[17].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[17].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[17].referencePoint = 70;
    std::cout << "CrossingObject_.Properties[17].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[17].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[17].type = 71;
    std::cout << "CrossingObject_.Properties[17].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[17].type) << std::dec  << std::endl;
    CrossingObject_.Properties[17].width = 236.50;
    std::cout << "CrossingObject_.Properties[17].width(float32): " << CrossingObject_.Properties[17].width << std::endl;
    CrossingObject_.Properties[17].length = 237.60;
    std::cout << "CrossingObject_.Properties[17].length(float32): " << CrossingObject_.Properties[17].length << std::endl;
    CrossingObject_.Properties[17].cmbbQly = 72;
    std::cout << "CrossingObject_.Properties[17].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[17].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[18].id = 19;
    std::cout << "CrossingObject_.Properties[18].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[18].id) << std::dec  << std::endl;
    CrossingObject_.Properties[18].motionPattern = 73;
    std::cout << "CrossingObject_.Properties[18].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[18].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[18].referencePoint = 74;
    std::cout << "CrossingObject_.Properties[18].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[18].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[18].type = 75;
    std::cout << "CrossingObject_.Properties[18].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[18].type) << std::dec  << std::endl;
    CrossingObject_.Properties[18].width = 238.70;
    std::cout << "CrossingObject_.Properties[18].width(float32): " << CrossingObject_.Properties[18].width << std::endl;
    CrossingObject_.Properties[18].length = 239.80;
    std::cout << "CrossingObject_.Properties[18].length(float32): " << CrossingObject_.Properties[18].length << std::endl;
    CrossingObject_.Properties[18].cmbbQly = 76;
    std::cout << "CrossingObject_.Properties[18].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[18].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[19].id = 20;
    std::cout << "CrossingObject_.Properties[19].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[19].id) << std::dec  << std::endl;
    CrossingObject_.Properties[19].motionPattern = 77;
    std::cout << "CrossingObject_.Properties[19].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[19].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[19].referencePoint = 78;
    std::cout << "CrossingObject_.Properties[19].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[19].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[19].type = 79;
    std::cout << "CrossingObject_.Properties[19].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[19].type) << std::dec  << std::endl;
    CrossingObject_.Properties[19].width = 240.90;
    std::cout << "CrossingObject_.Properties[19].width(float32): " << CrossingObject_.Properties[19].width << std::endl;
    CrossingObject_.Properties[19].length = 242.00;
    std::cout << "CrossingObject_.Properties[19].length(float32): " << CrossingObject_.Properties[19].length << std::endl;
    CrossingObject_.Properties[19].cmbbQly = 80;
    std::cout << "CrossingObject_.Properties[19].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[19].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[20].id = 21;
    std::cout << "CrossingObject_.Properties[20].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[20].id) << std::dec  << std::endl;
    CrossingObject_.Properties[20].motionPattern = 81;
    std::cout << "CrossingObject_.Properties[20].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[20].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[20].referencePoint = 82;
    std::cout << "CrossingObject_.Properties[20].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[20].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[20].type = 83;
    std::cout << "CrossingObject_.Properties[20].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[20].type) << std::dec  << std::endl;
    CrossingObject_.Properties[20].width = 243.10;
    std::cout << "CrossingObject_.Properties[20].width(float32): " << CrossingObject_.Properties[20].width << std::endl;
    CrossingObject_.Properties[20].length = 244.20;
    std::cout << "CrossingObject_.Properties[20].length(float32): " << CrossingObject_.Properties[20].length << std::endl;
    CrossingObject_.Properties[20].cmbbQly = 84;
    std::cout << "CrossingObject_.Properties[20].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[20].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[21].id = 22;
    std::cout << "CrossingObject_.Properties[21].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[21].id) << std::dec  << std::endl;
    CrossingObject_.Properties[21].motionPattern = 85;
    std::cout << "CrossingObject_.Properties[21].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[21].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[21].referencePoint = 86;
    std::cout << "CrossingObject_.Properties[21].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[21].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[21].type = 87;
    std::cout << "CrossingObject_.Properties[21].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[21].type) << std::dec  << std::endl;
    CrossingObject_.Properties[21].width = 245.30;
    std::cout << "CrossingObject_.Properties[21].width(float32): " << CrossingObject_.Properties[21].width << std::endl;
    CrossingObject_.Properties[21].length = 246.40;
    std::cout << "CrossingObject_.Properties[21].length(float32): " << CrossingObject_.Properties[21].length << std::endl;
    CrossingObject_.Properties[21].cmbbQly = 88;
    std::cout << "CrossingObject_.Properties[21].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[21].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[22].id = 23;
    std::cout << "CrossingObject_.Properties[22].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[22].id) << std::dec  << std::endl;
    CrossingObject_.Properties[22].motionPattern = 89;
    std::cout << "CrossingObject_.Properties[22].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[22].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[22].referencePoint = 90;
    std::cout << "CrossingObject_.Properties[22].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[22].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[22].type = 91;
    std::cout << "CrossingObject_.Properties[22].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[22].type) << std::dec  << std::endl;
    CrossingObject_.Properties[22].width = 247.50;
    std::cout << "CrossingObject_.Properties[22].width(float32): " << CrossingObject_.Properties[22].width << std::endl;
    CrossingObject_.Properties[22].length = 248.60;
    std::cout << "CrossingObject_.Properties[22].length(float32): " << CrossingObject_.Properties[22].length << std::endl;
    CrossingObject_.Properties[22].cmbbQly = 92;
    std::cout << "CrossingObject_.Properties[22].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[22].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[23].id = 24;
    std::cout << "CrossingObject_.Properties[23].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[23].id) << std::dec  << std::endl;
    CrossingObject_.Properties[23].motionPattern = 93;
    std::cout << "CrossingObject_.Properties[23].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[23].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[23].referencePoint = 94;
    std::cout << "CrossingObject_.Properties[23].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[23].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[23].type = 95;
    std::cout << "CrossingObject_.Properties[23].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[23].type) << std::dec  << std::endl;
    CrossingObject_.Properties[23].width = 249.70;
    std::cout << "CrossingObject_.Properties[23].width(float32): " << CrossingObject_.Properties[23].width << std::endl;
    CrossingObject_.Properties[23].length = 250.80;
    std::cout << "CrossingObject_.Properties[23].length(float32): " << CrossingObject_.Properties[23].length << std::endl;
    CrossingObject_.Properties[23].cmbbQly = 96;
    std::cout << "CrossingObject_.Properties[23].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[23].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[24].id = 25;
    std::cout << "CrossingObject_.Properties[24].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[24].id) << std::dec  << std::endl;
    CrossingObject_.Properties[24].motionPattern = 97;
    std::cout << "CrossingObject_.Properties[24].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[24].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[24].referencePoint = 98;
    std::cout << "CrossingObject_.Properties[24].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[24].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[24].type = 99;
    std::cout << "CrossingObject_.Properties[24].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[24].type) << std::dec  << std::endl;
    CrossingObject_.Properties[24].width = 251.90;
    std::cout << "CrossingObject_.Properties[24].width(float32): " << CrossingObject_.Properties[24].width << std::endl;
    CrossingObject_.Properties[24].length = 253.00;
    std::cout << "CrossingObject_.Properties[24].length(float32): " << CrossingObject_.Properties[24].length << std::endl;
    CrossingObject_.Properties[24].cmbbQly = 100;
    std::cout << "CrossingObject_.Properties[24].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[24].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[25].id = 26;
    std::cout << "CrossingObject_.Properties[25].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[25].id) << std::dec  << std::endl;
    CrossingObject_.Properties[25].motionPattern = 101;
    std::cout << "CrossingObject_.Properties[25].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[25].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[25].referencePoint = 102;
    std::cout << "CrossingObject_.Properties[25].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[25].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[25].type = 103;
    std::cout << "CrossingObject_.Properties[25].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[25].type) << std::dec  << std::endl;
    CrossingObject_.Properties[25].width = 254.10;
    std::cout << "CrossingObject_.Properties[25].width(float32): " << CrossingObject_.Properties[25].width << std::endl;
    CrossingObject_.Properties[25].length = 255.20;
    std::cout << "CrossingObject_.Properties[25].length(float32): " << CrossingObject_.Properties[25].length << std::endl;
    CrossingObject_.Properties[25].cmbbQly = 104;
    std::cout << "CrossingObject_.Properties[25].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[25].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[26].id = 27;
    std::cout << "CrossingObject_.Properties[26].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[26].id) << std::dec  << std::endl;
    CrossingObject_.Properties[26].motionPattern = 105;
    std::cout << "CrossingObject_.Properties[26].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[26].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[26].referencePoint = 106;
    std::cout << "CrossingObject_.Properties[26].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[26].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[26].type = 107;
    std::cout << "CrossingObject_.Properties[26].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[26].type) << std::dec  << std::endl;
    CrossingObject_.Properties[26].width = 256.30;
    std::cout << "CrossingObject_.Properties[26].width(float32): " << CrossingObject_.Properties[26].width << std::endl;
    CrossingObject_.Properties[26].length = 257.40;
    std::cout << "CrossingObject_.Properties[26].length(float32): " << CrossingObject_.Properties[26].length << std::endl;
    CrossingObject_.Properties[26].cmbbQly = 108;
    std::cout << "CrossingObject_.Properties[26].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[26].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[27].id = 28;
    std::cout << "CrossingObject_.Properties[27].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[27].id) << std::dec  << std::endl;
    CrossingObject_.Properties[27].motionPattern = 109;
    std::cout << "CrossingObject_.Properties[27].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[27].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[27].referencePoint = 110;
    std::cout << "CrossingObject_.Properties[27].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[27].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[27].type = 111;
    std::cout << "CrossingObject_.Properties[27].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[27].type) << std::dec  << std::endl;
    CrossingObject_.Properties[27].width = 258.50;
    std::cout << "CrossingObject_.Properties[27].width(float32): " << CrossingObject_.Properties[27].width << std::endl;
    CrossingObject_.Properties[27].length = 259.60;
    std::cout << "CrossingObject_.Properties[27].length(float32): " << CrossingObject_.Properties[27].length << std::endl;
    CrossingObject_.Properties[27].cmbbQly = 112;
    std::cout << "CrossingObject_.Properties[27].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[27].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[28].id = 29;
    std::cout << "CrossingObject_.Properties[28].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[28].id) << std::dec  << std::endl;
    CrossingObject_.Properties[28].motionPattern = 113;
    std::cout << "CrossingObject_.Properties[28].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[28].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[28].referencePoint = 114;
    std::cout << "CrossingObject_.Properties[28].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[28].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[28].type = 115;
    std::cout << "CrossingObject_.Properties[28].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[28].type) << std::dec  << std::endl;
    CrossingObject_.Properties[28].width = 260.70;
    std::cout << "CrossingObject_.Properties[28].width(float32): " << CrossingObject_.Properties[28].width << std::endl;
    CrossingObject_.Properties[28].length = 261.80;
    std::cout << "CrossingObject_.Properties[28].length(float32): " << CrossingObject_.Properties[28].length << std::endl;
    CrossingObject_.Properties[28].cmbbQly = 116;
    std::cout << "CrossingObject_.Properties[28].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[28].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.Properties[29].id = 30;
    std::cout << "CrossingObject_.Properties[29].id(uint16): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[29].id) << std::dec  << std::endl;
    CrossingObject_.Properties[29].motionPattern = 117;
    std::cout << "CrossingObject_.Properties[29].motionPattern(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[29].motionPattern) << std::dec  << std::endl;
    CrossingObject_.Properties[29].referencePoint = 118;
    std::cout << "CrossingObject_.Properties[29].referencePoint(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[29].referencePoint) << std::dec  << std::endl;
    CrossingObject_.Properties[29].type = 119;
    std::cout << "CrossingObject_.Properties[29].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[29].type) << std::dec  << std::endl;
    CrossingObject_.Properties[29].width = 262.90;
    std::cout << "CrossingObject_.Properties[29].width(float32): " << CrossingObject_.Properties[29].width << std::endl;
    CrossingObject_.Properties[29].length = 264.00;
    std::cout << "CrossingObject_.Properties[29].length(float32): " << CrossingObject_.Properties[29].length << std::endl;
    CrossingObject_.Properties[29].cmbbQly = 120;
    std::cout << "CrossingObject_.Properties[29].cmbbQly(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(CrossingObject_.Properties[29].cmbbQly) << std::dec  << std::endl;
    CrossingObject_.SequenceID = 1;
    std::cout << "CrossingObject_.SequenceID(uint32): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(CrossingObject_.SequenceID) << std::dec  << std::endl;
}









