#include"AdApter_RearObject_PUB.h"

void print_memory(const void* ptr, size_t size) {
    const unsigned char* bytes = static_cast<const unsigned char*>(ptr);
    for (size_t i = 0; i < size; ++i) {
        std::cout << std::hex << std::setw(2) << std::setfill('0') 
                  << static_cast<int>(bytes[i]) << " ";
    }
    std::cout << std::dec << std::endl;
}



AdApter_RearObjectPUB::AdApter_RearObjectPUB()
{
}
AdApter_RearObjectPUB::~AdApter_RearObjectPUB()
{
}
auto AdApter_RearObjectPUB::maxeye_midware_init()
{

return proto_info;
}


void AdApter_RearObjectPUB::run()
{
    int i=0;
    std::cout << "config file path: " << json_file.c_str() << std::endl;
    data_in.resize(sizeof(RearObject));
    MOS::communication::Init(json_file.c_str());
    MOS::utils::Register::get().register_version("libRearObjectPUB", "1.1.0");
    MOS::communication::ProtocolInfo proto_info;
    proto_info.protocol_type = MOS::communication::kProtocolShm;//kProtocolHybrid
    proto_info.shm_info.block_count = 10;
    proto_info.shm_info.block_size = data_in.size();
    proto_info.shm_info.fast_mode = false;
    auto pub = MOS::communication::Publisher::New(domiain_id, topic, proto_info);
    auto mos_msg = std::make_shared<MOS::message::Message>();
    std::this_thread::sleep_for(std::chrono::milliseconds(cycle_ms*3));//40ms


    RearObject RearObject_;
    setIntialValue_RearObject(RearObject_);

    while (true) {        
        data_in.resize(sizeof(RearObject_));
        std::memcpy(&data_in[0], &RearObject_, sizeof(RearObject_));
        auto data_ref = std::make_shared<MOS::message::DataRef>(const_cast<char*>(data_in.data()), data_in.size());
        mos_msg->SetDataRef(data_ref);
        auto now_time = MOS::TimeUtils::NowNsec();
        mos_msg->SetGenTimestamp(now_time);
        pub->Pub(mos_msg);
        std::this_thread::sleep_for(std::chrono::milliseconds(cycle_ms));//40ms
    }
}
int main()
{
#ifdef _WIN32
    char* path = nullptr;
    _get_pgmptr(&path);
    std::stringstream ss;
    ss << path;
    std::string fullPath(path);
    std::cout << "Running on Windows" << std::endl;
#endif
#ifdef __linux__
    std::string fullPath = std::filesystem::read_symlink("/proc/self/exe");
    std::cout << "Running RearObject_PUB on Linux"<< fullPath << std::endl;
#endif
    size_t pos = fullPath.find_last_of("\\/");
    std::string configPath = fullPath.substr(0, pos) + "/discovery_config.json";
    AdApter_RearObjectPUB objtest;
    objtest.json_file = configPath;
    objtest.run();
return 0;
}



/* Set and Print struct RearObject initial value */
void setIntialValue_RearObject(RearObject& RearObject_){
    std::cout << "Set struct RearObject variable and Publish:" << std::endl;
    RearObject_.EgoStates[0].heading = 1.10;
    std::cout << "RearObject_.EgoStates[0].heading(float32): " << RearObject_.EgoStates[0].heading << std::endl;
    RearObject_.EgoStates[0].latAcceleration = 2.20;
    std::cout << "RearObject_.EgoStates[0].latAcceleration(float32): " << RearObject_.EgoStates[0].latAcceleration << std::endl;
    RearObject_.EgoStates[0].latPosition = 3.30;
    std::cout << "RearObject_.EgoStates[0].latPosition(float32): " << RearObject_.EgoStates[0].latPosition << std::endl;
    RearObject_.EgoStates[0].latPositionPath = 4.40;
    std::cout << "RearObject_.EgoStates[0].latPositionPath(float32): " << RearObject_.EgoStates[0].latPositionPath << std::endl;
    RearObject_.EgoStates[0].latVelocity = 5.50;
    std::cout << "RearObject_.EgoStates[0].latVelocity(float32): " << RearObject_.EgoStates[0].latVelocity << std::endl;
    RearObject_.EgoStates[0].longAcceleration = 6.60;
    std::cout << "RearObject_.EgoStates[0].longAcceleration(float32): " << RearObject_.EgoStates[0].longAcceleration << std::endl;
    RearObject_.EgoStates[0].longPosition = 7.70;
    std::cout << "RearObject_.EgoStates[0].longPosition(float32): " << RearObject_.EgoStates[0].longPosition << std::endl;
    RearObject_.EgoStates[0].longPositionPath = 8.80;
    std::cout << "RearObject_.EgoStates[0].longPositionPath(float32): " << RearObject_.EgoStates[0].longPositionPath << std::endl;
    RearObject_.EgoStates[0].longVelocity = 9.90;
    std::cout << "RearObject_.EgoStates[0].longVelocity(float32): " << RearObject_.EgoStates[0].longVelocity << std::endl;
    RearObject_.EgoStates[1].heading = 11.00;
    std::cout << "RearObject_.EgoStates[1].heading(float32): " << RearObject_.EgoStates[1].heading << std::endl;
    RearObject_.EgoStates[1].latAcceleration = 12.10;
    std::cout << "RearObject_.EgoStates[1].latAcceleration(float32): " << RearObject_.EgoStates[1].latAcceleration << std::endl;
    RearObject_.EgoStates[1].latPosition = 13.20;
    std::cout << "RearObject_.EgoStates[1].latPosition(float32): " << RearObject_.EgoStates[1].latPosition << std::endl;
    RearObject_.EgoStates[1].latPositionPath = 14.30;
    std::cout << "RearObject_.EgoStates[1].latPositionPath(float32): " << RearObject_.EgoStates[1].latPositionPath << std::endl;
    RearObject_.EgoStates[1].latVelocity = 15.40;
    std::cout << "RearObject_.EgoStates[1].latVelocity(float32): " << RearObject_.EgoStates[1].latVelocity << std::endl;
    RearObject_.EgoStates[1].longAcceleration = 16.50;
    std::cout << "RearObject_.EgoStates[1].longAcceleration(float32): " << RearObject_.EgoStates[1].longAcceleration << std::endl;
    RearObject_.EgoStates[1].longPosition = 17.60;
    std::cout << "RearObject_.EgoStates[1].longPosition(float32): " << RearObject_.EgoStates[1].longPosition << std::endl;
    RearObject_.EgoStates[1].longPositionPath = 18.70;
    std::cout << "RearObject_.EgoStates[1].longPositionPath(float32): " << RearObject_.EgoStates[1].longPositionPath << std::endl;
    RearObject_.EgoStates[1].longVelocity = 19.80;
    std::cout << "RearObject_.EgoStates[1].longVelocity(float32): " << RearObject_.EgoStates[1].longVelocity << std::endl;
    RearObject_.EgoStates[2].heading = 20.90;
    std::cout << "RearObject_.EgoStates[2].heading(float32): " << RearObject_.EgoStates[2].heading << std::endl;
    RearObject_.EgoStates[2].latAcceleration = 22.00;
    std::cout << "RearObject_.EgoStates[2].latAcceleration(float32): " << RearObject_.EgoStates[2].latAcceleration << std::endl;
    RearObject_.EgoStates[2].latPosition = 23.10;
    std::cout << "RearObject_.EgoStates[2].latPosition(float32): " << RearObject_.EgoStates[2].latPosition << std::endl;
    RearObject_.EgoStates[2].latPositionPath = 24.20;
    std::cout << "RearObject_.EgoStates[2].latPositionPath(float32): " << RearObject_.EgoStates[2].latPositionPath << std::endl;
    RearObject_.EgoStates[2].latVelocity = 25.30;
    std::cout << "RearObject_.EgoStates[2].latVelocity(float32): " << RearObject_.EgoStates[2].latVelocity << std::endl;
    RearObject_.EgoStates[2].longAcceleration = 26.40;
    std::cout << "RearObject_.EgoStates[2].longAcceleration(float32): " << RearObject_.EgoStates[2].longAcceleration << std::endl;
    RearObject_.EgoStates[2].longPosition = 27.50;
    std::cout << "RearObject_.EgoStates[2].longPosition(float32): " << RearObject_.EgoStates[2].longPosition << std::endl;
    RearObject_.EgoStates[2].longPositionPath = 28.60;
    std::cout << "RearObject_.EgoStates[2].longPositionPath(float32): " << RearObject_.EgoStates[2].longPositionPath << std::endl;
    RearObject_.EgoStates[2].longVelocity = 29.70;
    std::cout << "RearObject_.EgoStates[2].longVelocity(float32): " << RearObject_.EgoStates[2].longVelocity << std::endl;
    RearObject_.EgoStates[3].heading = 30.80;
    std::cout << "RearObject_.EgoStates[3].heading(float32): " << RearObject_.EgoStates[3].heading << std::endl;
    RearObject_.EgoStates[3].latAcceleration = 31.90;
    std::cout << "RearObject_.EgoStates[3].latAcceleration(float32): " << RearObject_.EgoStates[3].latAcceleration << std::endl;
    RearObject_.EgoStates[3].latPosition = 33.00;
    std::cout << "RearObject_.EgoStates[3].latPosition(float32): " << RearObject_.EgoStates[3].latPosition << std::endl;
    RearObject_.EgoStates[3].latPositionPath = 34.10;
    std::cout << "RearObject_.EgoStates[3].latPositionPath(float32): " << RearObject_.EgoStates[3].latPositionPath << std::endl;
    RearObject_.EgoStates[3].latVelocity = 35.20;
    std::cout << "RearObject_.EgoStates[3].latVelocity(float32): " << RearObject_.EgoStates[3].latVelocity << std::endl;
    RearObject_.EgoStates[3].longAcceleration = 36.30;
    std::cout << "RearObject_.EgoStates[3].longAcceleration(float32): " << RearObject_.EgoStates[3].longAcceleration << std::endl;
    RearObject_.EgoStates[3].longPosition = 37.40;
    std::cout << "RearObject_.EgoStates[3].longPosition(float32): " << RearObject_.EgoStates[3].longPosition << std::endl;
    RearObject_.EgoStates[3].longPositionPath = 38.50;
    std::cout << "RearObject_.EgoStates[3].longPositionPath(float32): " << RearObject_.EgoStates[3].longPositionPath << std::endl;
    RearObject_.EgoStates[3].longVelocity = 39.60;
    std::cout << "RearObject_.EgoStates[3].longVelocity(float32): " << RearObject_.EgoStates[3].longVelocity << std::endl;
    RearObject_.EgoStates[4].heading = 40.70;
    std::cout << "RearObject_.EgoStates[4].heading(float32): " << RearObject_.EgoStates[4].heading << std::endl;
    RearObject_.EgoStates[4].latAcceleration = 41.80;
    std::cout << "RearObject_.EgoStates[4].latAcceleration(float32): " << RearObject_.EgoStates[4].latAcceleration << std::endl;
    RearObject_.EgoStates[4].latPosition = 42.90;
    std::cout << "RearObject_.EgoStates[4].latPosition(float32): " << RearObject_.EgoStates[4].latPosition << std::endl;
    RearObject_.EgoStates[4].latPositionPath = 44.00;
    std::cout << "RearObject_.EgoStates[4].latPositionPath(float32): " << RearObject_.EgoStates[4].latPositionPath << std::endl;
    RearObject_.EgoStates[4].latVelocity = 45.10;
    std::cout << "RearObject_.EgoStates[4].latVelocity(float32): " << RearObject_.EgoStates[4].latVelocity << std::endl;
    RearObject_.EgoStates[4].longAcceleration = 46.20;
    std::cout << "RearObject_.EgoStates[4].longAcceleration(float32): " << RearObject_.EgoStates[4].longAcceleration << std::endl;
    RearObject_.EgoStates[4].longPosition = 47.30;
    std::cout << "RearObject_.EgoStates[4].longPosition(float32): " << RearObject_.EgoStates[4].longPosition << std::endl;
    RearObject_.EgoStates[4].longPositionPath = 48.40;
    std::cout << "RearObject_.EgoStates[4].longPositionPath(float32): " << RearObject_.EgoStates[4].longPositionPath << std::endl;
    RearObject_.EgoStates[4].longVelocity = 49.50;
    std::cout << "RearObject_.EgoStates[4].longVelocity(float32): " << RearObject_.EgoStates[4].longVelocity << std::endl;
    RearObject_.EgoStates[5].heading = 50.60;
    std::cout << "RearObject_.EgoStates[5].heading(float32): " << RearObject_.EgoStates[5].heading << std::endl;
    RearObject_.EgoStates[5].latAcceleration = 51.70;
    std::cout << "RearObject_.EgoStates[5].latAcceleration(float32): " << RearObject_.EgoStates[5].latAcceleration << std::endl;
    RearObject_.EgoStates[5].latPosition = 52.80;
    std::cout << "RearObject_.EgoStates[5].latPosition(float32): " << RearObject_.EgoStates[5].latPosition << std::endl;
    RearObject_.EgoStates[5].latPositionPath = 53.90;
    std::cout << "RearObject_.EgoStates[5].latPositionPath(float32): " << RearObject_.EgoStates[5].latPositionPath << std::endl;
    RearObject_.EgoStates[5].latVelocity = 55.00;
    std::cout << "RearObject_.EgoStates[5].latVelocity(float32): " << RearObject_.EgoStates[5].latVelocity << std::endl;
    RearObject_.EgoStates[5].longAcceleration = 56.10;
    std::cout << "RearObject_.EgoStates[5].longAcceleration(float32): " << RearObject_.EgoStates[5].longAcceleration << std::endl;
    RearObject_.EgoStates[5].longPosition = 57.20;
    std::cout << "RearObject_.EgoStates[5].longPosition(float32): " << RearObject_.EgoStates[5].longPosition << std::endl;
    RearObject_.EgoStates[5].longPositionPath = 58.30;
    std::cout << "RearObject_.EgoStates[5].longPositionPath(float32): " << RearObject_.EgoStates[5].longPositionPath << std::endl;
    RearObject_.EgoStates[5].longVelocity = 59.40;
    std::cout << "RearObject_.EgoStates[5].longVelocity(float32): " << RearObject_.EgoStates[5].longVelocity << std::endl;
    RearObject_.EgoStates[6].heading = 60.50;
    std::cout << "RearObject_.EgoStates[6].heading(float32): " << RearObject_.EgoStates[6].heading << std::endl;
    RearObject_.EgoStates[6].latAcceleration = 61.60;
    std::cout << "RearObject_.EgoStates[6].latAcceleration(float32): " << RearObject_.EgoStates[6].latAcceleration << std::endl;
    RearObject_.EgoStates[6].latPosition = 62.70;
    std::cout << "RearObject_.EgoStates[6].latPosition(float32): " << RearObject_.EgoStates[6].latPosition << std::endl;
    RearObject_.EgoStates[6].latPositionPath = 63.80;
    std::cout << "RearObject_.EgoStates[6].latPositionPath(float32): " << RearObject_.EgoStates[6].latPositionPath << std::endl;
    RearObject_.EgoStates[6].latVelocity = 64.90;
    std::cout << "RearObject_.EgoStates[6].latVelocity(float32): " << RearObject_.EgoStates[6].latVelocity << std::endl;
    RearObject_.EgoStates[6].longAcceleration = 66.00;
    std::cout << "RearObject_.EgoStates[6].longAcceleration(float32): " << RearObject_.EgoStates[6].longAcceleration << std::endl;
    RearObject_.EgoStates[6].longPosition = 67.10;
    std::cout << "RearObject_.EgoStates[6].longPosition(float32): " << RearObject_.EgoStates[6].longPosition << std::endl;
    RearObject_.EgoStates[6].longPositionPath = 68.20;
    std::cout << "RearObject_.EgoStates[6].longPositionPath(float32): " << RearObject_.EgoStates[6].longPositionPath << std::endl;
    RearObject_.EgoStates[6].longVelocity = 69.30;
    std::cout << "RearObject_.EgoStates[6].longVelocity(float32): " << RearObject_.EgoStates[6].longVelocity << std::endl;
    RearObject_.EgoStates[7].heading = 70.40;
    std::cout << "RearObject_.EgoStates[7].heading(float32): " << RearObject_.EgoStates[7].heading << std::endl;
    RearObject_.EgoStates[7].latAcceleration = 71.50;
    std::cout << "RearObject_.EgoStates[7].latAcceleration(float32): " << RearObject_.EgoStates[7].latAcceleration << std::endl;
    RearObject_.EgoStates[7].latPosition = 72.60;
    std::cout << "RearObject_.EgoStates[7].latPosition(float32): " << RearObject_.EgoStates[7].latPosition << std::endl;
    RearObject_.EgoStates[7].latPositionPath = 73.70;
    std::cout << "RearObject_.EgoStates[7].latPositionPath(float32): " << RearObject_.EgoStates[7].latPositionPath << std::endl;
    RearObject_.EgoStates[7].latVelocity = 74.80;
    std::cout << "RearObject_.EgoStates[7].latVelocity(float32): " << RearObject_.EgoStates[7].latVelocity << std::endl;
    RearObject_.EgoStates[7].longAcceleration = 75.90;
    std::cout << "RearObject_.EgoStates[7].longAcceleration(float32): " << RearObject_.EgoStates[7].longAcceleration << std::endl;
    RearObject_.EgoStates[7].longPosition = 77.00;
    std::cout << "RearObject_.EgoStates[7].longPosition(float32): " << RearObject_.EgoStates[7].longPosition << std::endl;
    RearObject_.EgoStates[7].longPositionPath = 78.10;
    std::cout << "RearObject_.EgoStates[7].longPositionPath(float32): " << RearObject_.EgoStates[7].longPositionPath << std::endl;
    RearObject_.EgoStates[7].longVelocity = 79.20;
    std::cout << "RearObject_.EgoStates[7].longVelocity(float32): " << RearObject_.EgoStates[7].longVelocity << std::endl;
    RearObject_.EgoStates[8].heading = 80.30;
    std::cout << "RearObject_.EgoStates[8].heading(float32): " << RearObject_.EgoStates[8].heading << std::endl;
    RearObject_.EgoStates[8].latAcceleration = 81.40;
    std::cout << "RearObject_.EgoStates[8].latAcceleration(float32): " << RearObject_.EgoStates[8].latAcceleration << std::endl;
    RearObject_.EgoStates[8].latPosition = 82.50;
    std::cout << "RearObject_.EgoStates[8].latPosition(float32): " << RearObject_.EgoStates[8].latPosition << std::endl;
    RearObject_.EgoStates[8].latPositionPath = 83.60;
    std::cout << "RearObject_.EgoStates[8].latPositionPath(float32): " << RearObject_.EgoStates[8].latPositionPath << std::endl;
    RearObject_.EgoStates[8].latVelocity = 84.70;
    std::cout << "RearObject_.EgoStates[8].latVelocity(float32): " << RearObject_.EgoStates[8].latVelocity << std::endl;
    RearObject_.EgoStates[8].longAcceleration = 85.80;
    std::cout << "RearObject_.EgoStates[8].longAcceleration(float32): " << RearObject_.EgoStates[8].longAcceleration << std::endl;
    RearObject_.EgoStates[8].longPosition = 86.90;
    std::cout << "RearObject_.EgoStates[8].longPosition(float32): " << RearObject_.EgoStates[8].longPosition << std::endl;
    RearObject_.EgoStates[8].longPositionPath = 88.00;
    std::cout << "RearObject_.EgoStates[8].longPositionPath(float32): " << RearObject_.EgoStates[8].longPositionPath << std::endl;
    RearObject_.EgoStates[8].longVelocity = 89.10;
    std::cout << "RearObject_.EgoStates[8].longVelocity(float32): " << RearObject_.EgoStates[8].longVelocity << std::endl;
    RearObject_.EgoStates[9].heading = 90.20;
    std::cout << "RearObject_.EgoStates[9].heading(float32): " << RearObject_.EgoStates[9].heading << std::endl;
    RearObject_.EgoStates[9].latAcceleration = 91.30;
    std::cout << "RearObject_.EgoStates[9].latAcceleration(float32): " << RearObject_.EgoStates[9].latAcceleration << std::endl;
    RearObject_.EgoStates[9].latPosition = 92.40;
    std::cout << "RearObject_.EgoStates[9].latPosition(float32): " << RearObject_.EgoStates[9].latPosition << std::endl;
    RearObject_.EgoStates[9].latPositionPath = 93.50;
    std::cout << "RearObject_.EgoStates[9].latPositionPath(float32): " << RearObject_.EgoStates[9].latPositionPath << std::endl;
    RearObject_.EgoStates[9].latVelocity = 94.60;
    std::cout << "RearObject_.EgoStates[9].latVelocity(float32): " << RearObject_.EgoStates[9].latVelocity << std::endl;
    RearObject_.EgoStates[9].longAcceleration = 95.70;
    std::cout << "RearObject_.EgoStates[9].longAcceleration(float32): " << RearObject_.EgoStates[9].longAcceleration << std::endl;
    RearObject_.EgoStates[9].longPosition = 96.80;
    std::cout << "RearObject_.EgoStates[9].longPosition(float32): " << RearObject_.EgoStates[9].longPosition << std::endl;
    RearObject_.EgoStates[9].longPositionPath = 97.90;
    std::cout << "RearObject_.EgoStates[9].longPositionPath(float32): " << RearObject_.EgoStates[9].longPositionPath << std::endl;
    RearObject_.EgoStates[9].longVelocity = 99.00;
    std::cout << "RearObject_.EgoStates[9].longVelocity(float32): " << RearObject_.EgoStates[9].longVelocity << std::endl;
    RearObject_.RoadStates[0].headingRoad = 100.10;
    std::cout << "RearObject_.RoadStates[0].headingRoad(float32): " << RearObject_.RoadStates[0].headingRoad << std::endl;
    RearObject_.RoadStates[0].latAccelerationRoad = 101.20;
    std::cout << "RearObject_.RoadStates[0].latAccelerationRoad(float32): " << RearObject_.RoadStates[0].latAccelerationRoad << std::endl;
    RearObject_.RoadStates[0].latPositionRoad = 102.30;
    std::cout << "RearObject_.RoadStates[0].latPositionRoad(float32): " << RearObject_.RoadStates[0].latPositionRoad << std::endl;
    RearObject_.RoadStates[0].latVelocityRoad = 103.40;
    std::cout << "RearObject_.RoadStates[0].latVelocityRoad(float32): " << RearObject_.RoadStates[0].latVelocityRoad << std::endl;
    RearObject_.RoadStates[0].longAccelerationRoad = 104.50;
    std::cout << "RearObject_.RoadStates[0].longAccelerationRoad(float32): " << RearObject_.RoadStates[0].longAccelerationRoad << std::endl;
    RearObject_.RoadStates[0].longPositionRoad = 105.60;
    std::cout << "RearObject_.RoadStates[0].longPositionRoad(float32): " << RearObject_.RoadStates[0].longPositionRoad << std::endl;
    RearObject_.RoadStates[0].longVelocityRoad = 106.70;
    std::cout << "RearObject_.RoadStates[0].longVelocityRoad(float32): " << RearObject_.RoadStates[0].longVelocityRoad << std::endl;
    RearObject_.RoadStates[1].headingRoad = 107.80;
    std::cout << "RearObject_.RoadStates[1].headingRoad(float32): " << RearObject_.RoadStates[1].headingRoad << std::endl;
    RearObject_.RoadStates[1].latAccelerationRoad = 108.90;
    std::cout << "RearObject_.RoadStates[1].latAccelerationRoad(float32): " << RearObject_.RoadStates[1].latAccelerationRoad << std::endl;
    RearObject_.RoadStates[1].latPositionRoad = 110.00;
    std::cout << "RearObject_.RoadStates[1].latPositionRoad(float32): " << RearObject_.RoadStates[1].latPositionRoad << std::endl;
    RearObject_.RoadStates[1].latVelocityRoad = 111.10;
    std::cout << "RearObject_.RoadStates[1].latVelocityRoad(float32): " << RearObject_.RoadStates[1].latVelocityRoad << std::endl;
    RearObject_.RoadStates[1].longAccelerationRoad = 112.20;
    std::cout << "RearObject_.RoadStates[1].longAccelerationRoad(float32): " << RearObject_.RoadStates[1].longAccelerationRoad << std::endl;
    RearObject_.RoadStates[1].longPositionRoad = 113.30;
    std::cout << "RearObject_.RoadStates[1].longPositionRoad(float32): " << RearObject_.RoadStates[1].longPositionRoad << std::endl;
    RearObject_.RoadStates[1].longVelocityRoad = 114.40;
    std::cout << "RearObject_.RoadStates[1].longVelocityRoad(float32): " << RearObject_.RoadStates[1].longVelocityRoad << std::endl;
    RearObject_.RoadStates[2].headingRoad = 115.50;
    std::cout << "RearObject_.RoadStates[2].headingRoad(float32): " << RearObject_.RoadStates[2].headingRoad << std::endl;
    RearObject_.RoadStates[2].latAccelerationRoad = 116.60;
    std::cout << "RearObject_.RoadStates[2].latAccelerationRoad(float32): " << RearObject_.RoadStates[2].latAccelerationRoad << std::endl;
    RearObject_.RoadStates[2].latPositionRoad = 117.70;
    std::cout << "RearObject_.RoadStates[2].latPositionRoad(float32): " << RearObject_.RoadStates[2].latPositionRoad << std::endl;
    RearObject_.RoadStates[2].latVelocityRoad = 118.80;
    std::cout << "RearObject_.RoadStates[2].latVelocityRoad(float32): " << RearObject_.RoadStates[2].latVelocityRoad << std::endl;
    RearObject_.RoadStates[2].longAccelerationRoad = 119.90;
    std::cout << "RearObject_.RoadStates[2].longAccelerationRoad(float32): " << RearObject_.RoadStates[2].longAccelerationRoad << std::endl;
    RearObject_.RoadStates[2].longPositionRoad = 121.00;
    std::cout << "RearObject_.RoadStates[2].longPositionRoad(float32): " << RearObject_.RoadStates[2].longPositionRoad << std::endl;
    RearObject_.RoadStates[2].longVelocityRoad = 122.10;
    std::cout << "RearObject_.RoadStates[2].longVelocityRoad(float32): " << RearObject_.RoadStates[2].longVelocityRoad << std::endl;
    RearObject_.RoadStates[3].headingRoad = 123.20;
    std::cout << "RearObject_.RoadStates[3].headingRoad(float32): " << RearObject_.RoadStates[3].headingRoad << std::endl;
    RearObject_.RoadStates[3].latAccelerationRoad = 124.30;
    std::cout << "RearObject_.RoadStates[3].latAccelerationRoad(float32): " << RearObject_.RoadStates[3].latAccelerationRoad << std::endl;
    RearObject_.RoadStates[3].latPositionRoad = 125.40;
    std::cout << "RearObject_.RoadStates[3].latPositionRoad(float32): " << RearObject_.RoadStates[3].latPositionRoad << std::endl;
    RearObject_.RoadStates[3].latVelocityRoad = 126.50;
    std::cout << "RearObject_.RoadStates[3].latVelocityRoad(float32): " << RearObject_.RoadStates[3].latVelocityRoad << std::endl;
    RearObject_.RoadStates[3].longAccelerationRoad = 127.60;
    std::cout << "RearObject_.RoadStates[3].longAccelerationRoad(float32): " << RearObject_.RoadStates[3].longAccelerationRoad << std::endl;
    RearObject_.RoadStates[3].longPositionRoad = 128.70;
    std::cout << "RearObject_.RoadStates[3].longPositionRoad(float32): " << RearObject_.RoadStates[3].longPositionRoad << std::endl;
    RearObject_.RoadStates[3].longVelocityRoad = 129.80;
    std::cout << "RearObject_.RoadStates[3].longVelocityRoad(float32): " << RearObject_.RoadStates[3].longVelocityRoad << std::endl;
    RearObject_.RoadStates[4].headingRoad = 130.90;
    std::cout << "RearObject_.RoadStates[4].headingRoad(float32): " << RearObject_.RoadStates[4].headingRoad << std::endl;
    RearObject_.RoadStates[4].latAccelerationRoad = 132.00;
    std::cout << "RearObject_.RoadStates[4].latAccelerationRoad(float32): " << RearObject_.RoadStates[4].latAccelerationRoad << std::endl;
    RearObject_.RoadStates[4].latPositionRoad = 133.10;
    std::cout << "RearObject_.RoadStates[4].latPositionRoad(float32): " << RearObject_.RoadStates[4].latPositionRoad << std::endl;
    RearObject_.RoadStates[4].latVelocityRoad = 134.20;
    std::cout << "RearObject_.RoadStates[4].latVelocityRoad(float32): " << RearObject_.RoadStates[4].latVelocityRoad << std::endl;
    RearObject_.RoadStates[4].longAccelerationRoad = 135.30;
    std::cout << "RearObject_.RoadStates[4].longAccelerationRoad(float32): " << RearObject_.RoadStates[4].longAccelerationRoad << std::endl;
    RearObject_.RoadStates[4].longPositionRoad = 136.40;
    std::cout << "RearObject_.RoadStates[4].longPositionRoad(float32): " << RearObject_.RoadStates[4].longPositionRoad << std::endl;
    RearObject_.RoadStates[4].longVelocityRoad = 137.50;
    std::cout << "RearObject_.RoadStates[4].longVelocityRoad(float32): " << RearObject_.RoadStates[4].longVelocityRoad << std::endl;
    RearObject_.RoadStates[5].headingRoad = 138.60;
    std::cout << "RearObject_.RoadStates[5].headingRoad(float32): " << RearObject_.RoadStates[5].headingRoad << std::endl;
    RearObject_.RoadStates[5].latAccelerationRoad = 139.70;
    std::cout << "RearObject_.RoadStates[5].latAccelerationRoad(float32): " << RearObject_.RoadStates[5].latAccelerationRoad << std::endl;
    RearObject_.RoadStates[5].latPositionRoad = 140.80;
    std::cout << "RearObject_.RoadStates[5].latPositionRoad(float32): " << RearObject_.RoadStates[5].latPositionRoad << std::endl;
    RearObject_.RoadStates[5].latVelocityRoad = 141.90;
    std::cout << "RearObject_.RoadStates[5].latVelocityRoad(float32): " << RearObject_.RoadStates[5].latVelocityRoad << std::endl;
    RearObject_.RoadStates[5].longAccelerationRoad = 143.00;
    std::cout << "RearObject_.RoadStates[5].longAccelerationRoad(float32): " << RearObject_.RoadStates[5].longAccelerationRoad << std::endl;
    RearObject_.RoadStates[5].longPositionRoad = 144.10;
    std::cout << "RearObject_.RoadStates[5].longPositionRoad(float32): " << RearObject_.RoadStates[5].longPositionRoad << std::endl;
    RearObject_.RoadStates[5].longVelocityRoad = 145.20;
    std::cout << "RearObject_.RoadStates[5].longVelocityRoad(float32): " << RearObject_.RoadStates[5].longVelocityRoad << std::endl;
    RearObject_.RoadStates[6].headingRoad = 146.30;
    std::cout << "RearObject_.RoadStates[6].headingRoad(float32): " << RearObject_.RoadStates[6].headingRoad << std::endl;
    RearObject_.RoadStates[6].latAccelerationRoad = 147.40;
    std::cout << "RearObject_.RoadStates[6].latAccelerationRoad(float32): " << RearObject_.RoadStates[6].latAccelerationRoad << std::endl;
    RearObject_.RoadStates[6].latPositionRoad = 148.50;
    std::cout << "RearObject_.RoadStates[6].latPositionRoad(float32): " << RearObject_.RoadStates[6].latPositionRoad << std::endl;
    RearObject_.RoadStates[6].latVelocityRoad = 149.60;
    std::cout << "RearObject_.RoadStates[6].latVelocityRoad(float32): " << RearObject_.RoadStates[6].latVelocityRoad << std::endl;
    RearObject_.RoadStates[6].longAccelerationRoad = 150.70;
    std::cout << "RearObject_.RoadStates[6].longAccelerationRoad(float32): " << RearObject_.RoadStates[6].longAccelerationRoad << std::endl;
    RearObject_.RoadStates[6].longPositionRoad = 151.80;
    std::cout << "RearObject_.RoadStates[6].longPositionRoad(float32): " << RearObject_.RoadStates[6].longPositionRoad << std::endl;
    RearObject_.RoadStates[6].longVelocityRoad = 152.90;
    std::cout << "RearObject_.RoadStates[6].longVelocityRoad(float32): " << RearObject_.RoadStates[6].longVelocityRoad << std::endl;
    RearObject_.RoadStates[7].headingRoad = 154.00;
    std::cout << "RearObject_.RoadStates[7].headingRoad(float32): " << RearObject_.RoadStates[7].headingRoad << std::endl;
    RearObject_.RoadStates[7].latAccelerationRoad = 155.10;
    std::cout << "RearObject_.RoadStates[7].latAccelerationRoad(float32): " << RearObject_.RoadStates[7].latAccelerationRoad << std::endl;
    RearObject_.RoadStates[7].latPositionRoad = 156.20;
    std::cout << "RearObject_.RoadStates[7].latPositionRoad(float32): " << RearObject_.RoadStates[7].latPositionRoad << std::endl;
    RearObject_.RoadStates[7].latVelocityRoad = 157.30;
    std::cout << "RearObject_.RoadStates[7].latVelocityRoad(float32): " << RearObject_.RoadStates[7].latVelocityRoad << std::endl;
    RearObject_.RoadStates[7].longAccelerationRoad = 158.40;
    std::cout << "RearObject_.RoadStates[7].longAccelerationRoad(float32): " << RearObject_.RoadStates[7].longAccelerationRoad << std::endl;
    RearObject_.RoadStates[7].longPositionRoad = 159.50;
    std::cout << "RearObject_.RoadStates[7].longPositionRoad(float32): " << RearObject_.RoadStates[7].longPositionRoad << std::endl;
    RearObject_.RoadStates[7].longVelocityRoad = 160.60;
    std::cout << "RearObject_.RoadStates[7].longVelocityRoad(float32): " << RearObject_.RoadStates[7].longVelocityRoad << std::endl;
    RearObject_.RoadStates[8].headingRoad = 161.70;
    std::cout << "RearObject_.RoadStates[8].headingRoad(float32): " << RearObject_.RoadStates[8].headingRoad << std::endl;
    RearObject_.RoadStates[8].latAccelerationRoad = 162.80;
    std::cout << "RearObject_.RoadStates[8].latAccelerationRoad(float32): " << RearObject_.RoadStates[8].latAccelerationRoad << std::endl;
    RearObject_.RoadStates[8].latPositionRoad = 163.90;
    std::cout << "RearObject_.RoadStates[8].latPositionRoad(float32): " << RearObject_.RoadStates[8].latPositionRoad << std::endl;
    RearObject_.RoadStates[8].latVelocityRoad = 165.00;
    std::cout << "RearObject_.RoadStates[8].latVelocityRoad(float32): " << RearObject_.RoadStates[8].latVelocityRoad << std::endl;
    RearObject_.RoadStates[8].longAccelerationRoad = 166.10;
    std::cout << "RearObject_.RoadStates[8].longAccelerationRoad(float32): " << RearObject_.RoadStates[8].longAccelerationRoad << std::endl;
    RearObject_.RoadStates[8].longPositionRoad = 167.20;
    std::cout << "RearObject_.RoadStates[8].longPositionRoad(float32): " << RearObject_.RoadStates[8].longPositionRoad << std::endl;
    RearObject_.RoadStates[8].longVelocityRoad = 168.30;
    std::cout << "RearObject_.RoadStates[8].longVelocityRoad(float32): " << RearObject_.RoadStates[8].longVelocityRoad << std::endl;
    RearObject_.RoadStates[9].headingRoad = 169.40;
    std::cout << "RearObject_.RoadStates[9].headingRoad(float32): " << RearObject_.RoadStates[9].headingRoad << std::endl;
    RearObject_.RoadStates[9].latAccelerationRoad = 170.50;
    std::cout << "RearObject_.RoadStates[9].latAccelerationRoad(float32): " << RearObject_.RoadStates[9].latAccelerationRoad << std::endl;
    RearObject_.RoadStates[9].latPositionRoad = 171.60;
    std::cout << "RearObject_.RoadStates[9].latPositionRoad(float32): " << RearObject_.RoadStates[9].latPositionRoad << std::endl;
    RearObject_.RoadStates[9].latVelocityRoad = 172.70;
    std::cout << "RearObject_.RoadStates[9].latVelocityRoad(float32): " << RearObject_.RoadStates[9].latVelocityRoad << std::endl;
    RearObject_.RoadStates[9].longAccelerationRoad = 173.80;
    std::cout << "RearObject_.RoadStates[9].longAccelerationRoad(float32): " << RearObject_.RoadStates[9].longAccelerationRoad << std::endl;
    RearObject_.RoadStates[9].longPositionRoad = 174.90;
    std::cout << "RearObject_.RoadStates[9].longPositionRoad(float32): " << RearObject_.RoadStates[9].longPositionRoad << std::endl;
    RearObject_.RoadStates[9].longVelocityRoad = 176.00;
    std::cout << "RearObject_.RoadStates[9].longVelocityRoad(float32): " << RearObject_.RoadStates[9].longVelocityRoad << std::endl;
    RearObject_.Properties[0].latPositionConfidence = 1;
    std::cout << "RearObject_.Properties[0].latPositionConfidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[0].latPositionConfidence) << std::dec  << std::endl;
    RearObject_.Properties[0].length = 177.10;
    std::cout << "RearObject_.Properties[0].length(float32): " << RearObject_.Properties[0].length << std::endl;
    RearObject_.Properties[0].confidence = 2;
    std::cout << "RearObject_.Properties[0].confidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[0].confidence) << std::dec  << std::endl;
    RearObject_.Properties[0].type = 3;
    std::cout << "RearObject_.Properties[0].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[0].type) << std::dec  << std::endl;
    RearObject_.Properties[0].width = 178.20;
    std::cout << "RearObject_.Properties[0].width(float32): " << RearObject_.Properties[0].width << std::endl;
    RearObject_.Properties[0].id = 4;
    std::cout << "RearObject_.Properties[0].id(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[0].id) << std::dec  << std::endl;
    RearObject_.Properties[0].trackStatus = 5;
    std::cout << "RearObject_.Properties[0].trackStatus(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[0].trackStatus) << std::dec  << std::endl;
    RearObject_.Properties[1].latPositionConfidence = 6;
    std::cout << "RearObject_.Properties[1].latPositionConfidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[1].latPositionConfidence) << std::dec  << std::endl;
    RearObject_.Properties[1].length = 179.30;
    std::cout << "RearObject_.Properties[1].length(float32): " << RearObject_.Properties[1].length << std::endl;
    RearObject_.Properties[1].confidence = 7;
    std::cout << "RearObject_.Properties[1].confidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[1].confidence) << std::dec  << std::endl;
    RearObject_.Properties[1].type = 8;
    std::cout << "RearObject_.Properties[1].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[1].type) << std::dec  << std::endl;
    RearObject_.Properties[1].width = 180.40;
    std::cout << "RearObject_.Properties[1].width(float32): " << RearObject_.Properties[1].width << std::endl;
    RearObject_.Properties[1].id = 9;
    std::cout << "RearObject_.Properties[1].id(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[1].id) << std::dec  << std::endl;
    RearObject_.Properties[1].trackStatus = 10;
    std::cout << "RearObject_.Properties[1].trackStatus(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[1].trackStatus) << std::dec  << std::endl;
    RearObject_.Properties[2].latPositionConfidence = 11;
    std::cout << "RearObject_.Properties[2].latPositionConfidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[2].latPositionConfidence) << std::dec  << std::endl;
    RearObject_.Properties[2].length = 181.50;
    std::cout << "RearObject_.Properties[2].length(float32): " << RearObject_.Properties[2].length << std::endl;
    RearObject_.Properties[2].confidence = 12;
    std::cout << "RearObject_.Properties[2].confidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[2].confidence) << std::dec  << std::endl;
    RearObject_.Properties[2].type = 13;
    std::cout << "RearObject_.Properties[2].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[2].type) << std::dec  << std::endl;
    RearObject_.Properties[2].width = 182.60;
    std::cout << "RearObject_.Properties[2].width(float32): " << RearObject_.Properties[2].width << std::endl;
    RearObject_.Properties[2].id = 14;
    std::cout << "RearObject_.Properties[2].id(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[2].id) << std::dec  << std::endl;
    RearObject_.Properties[2].trackStatus = 15;
    std::cout << "RearObject_.Properties[2].trackStatus(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[2].trackStatus) << std::dec  << std::endl;
    RearObject_.Properties[3].latPositionConfidence = 16;
    std::cout << "RearObject_.Properties[3].latPositionConfidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[3].latPositionConfidence) << std::dec  << std::endl;
    RearObject_.Properties[3].length = 183.70;
    std::cout << "RearObject_.Properties[3].length(float32): " << RearObject_.Properties[3].length << std::endl;
    RearObject_.Properties[3].confidence = 17;
    std::cout << "RearObject_.Properties[3].confidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[3].confidence) << std::dec  << std::endl;
    RearObject_.Properties[3].type = 18;
    std::cout << "RearObject_.Properties[3].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[3].type) << std::dec  << std::endl;
    RearObject_.Properties[3].width = 184.80;
    std::cout << "RearObject_.Properties[3].width(float32): " << RearObject_.Properties[3].width << std::endl;
    RearObject_.Properties[3].id = 19;
    std::cout << "RearObject_.Properties[3].id(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[3].id) << std::dec  << std::endl;
    RearObject_.Properties[3].trackStatus = 20;
    std::cout << "RearObject_.Properties[3].trackStatus(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[3].trackStatus) << std::dec  << std::endl;
    RearObject_.Properties[4].latPositionConfidence = 21;
    std::cout << "RearObject_.Properties[4].latPositionConfidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[4].latPositionConfidence) << std::dec  << std::endl;
    RearObject_.Properties[4].length = 185.90;
    std::cout << "RearObject_.Properties[4].length(float32): " << RearObject_.Properties[4].length << std::endl;
    RearObject_.Properties[4].confidence = 22;
    std::cout << "RearObject_.Properties[4].confidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[4].confidence) << std::dec  << std::endl;
    RearObject_.Properties[4].type = 23;
    std::cout << "RearObject_.Properties[4].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[4].type) << std::dec  << std::endl;
    RearObject_.Properties[4].width = 187.00;
    std::cout << "RearObject_.Properties[4].width(float32): " << RearObject_.Properties[4].width << std::endl;
    RearObject_.Properties[4].id = 24;
    std::cout << "RearObject_.Properties[4].id(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[4].id) << std::dec  << std::endl;
    RearObject_.Properties[4].trackStatus = 25;
    std::cout << "RearObject_.Properties[4].trackStatus(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[4].trackStatus) << std::dec  << std::endl;
    RearObject_.Properties[5].latPositionConfidence = 26;
    std::cout << "RearObject_.Properties[5].latPositionConfidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[5].latPositionConfidence) << std::dec  << std::endl;
    RearObject_.Properties[5].length = 188.10;
    std::cout << "RearObject_.Properties[5].length(float32): " << RearObject_.Properties[5].length << std::endl;
    RearObject_.Properties[5].confidence = 27;
    std::cout << "RearObject_.Properties[5].confidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[5].confidence) << std::dec  << std::endl;
    RearObject_.Properties[5].type = 28;
    std::cout << "RearObject_.Properties[5].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[5].type) << std::dec  << std::endl;
    RearObject_.Properties[5].width = 189.20;
    std::cout << "RearObject_.Properties[5].width(float32): " << RearObject_.Properties[5].width << std::endl;
    RearObject_.Properties[5].id = 29;
    std::cout << "RearObject_.Properties[5].id(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[5].id) << std::dec  << std::endl;
    RearObject_.Properties[5].trackStatus = 30;
    std::cout << "RearObject_.Properties[5].trackStatus(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[5].trackStatus) << std::dec  << std::endl;
    RearObject_.Properties[6].latPositionConfidence = 31;
    std::cout << "RearObject_.Properties[6].latPositionConfidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[6].latPositionConfidence) << std::dec  << std::endl;
    RearObject_.Properties[6].length = 190.30;
    std::cout << "RearObject_.Properties[6].length(float32): " << RearObject_.Properties[6].length << std::endl;
    RearObject_.Properties[6].confidence = 32;
    std::cout << "RearObject_.Properties[6].confidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[6].confidence) << std::dec  << std::endl;
    RearObject_.Properties[6].type = 33;
    std::cout << "RearObject_.Properties[6].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[6].type) << std::dec  << std::endl;
    RearObject_.Properties[6].width = 191.40;
    std::cout << "RearObject_.Properties[6].width(float32): " << RearObject_.Properties[6].width << std::endl;
    RearObject_.Properties[6].id = 34;
    std::cout << "RearObject_.Properties[6].id(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[6].id) << std::dec  << std::endl;
    RearObject_.Properties[6].trackStatus = 35;
    std::cout << "RearObject_.Properties[6].trackStatus(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[6].trackStatus) << std::dec  << std::endl;
    RearObject_.Properties[7].latPositionConfidence = 36;
    std::cout << "RearObject_.Properties[7].latPositionConfidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[7].latPositionConfidence) << std::dec  << std::endl;
    RearObject_.Properties[7].length = 192.50;
    std::cout << "RearObject_.Properties[7].length(float32): " << RearObject_.Properties[7].length << std::endl;
    RearObject_.Properties[7].confidence = 37;
    std::cout << "RearObject_.Properties[7].confidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[7].confidence) << std::dec  << std::endl;
    RearObject_.Properties[7].type = 38;
    std::cout << "RearObject_.Properties[7].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[7].type) << std::dec  << std::endl;
    RearObject_.Properties[7].width = 193.60;
    std::cout << "RearObject_.Properties[7].width(float32): " << RearObject_.Properties[7].width << std::endl;
    RearObject_.Properties[7].id = 39;
    std::cout << "RearObject_.Properties[7].id(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[7].id) << std::dec  << std::endl;
    RearObject_.Properties[7].trackStatus = 40;
    std::cout << "RearObject_.Properties[7].trackStatus(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[7].trackStatus) << std::dec  << std::endl;
    RearObject_.Properties[8].latPositionConfidence = 41;
    std::cout << "RearObject_.Properties[8].latPositionConfidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[8].latPositionConfidence) << std::dec  << std::endl;
    RearObject_.Properties[8].length = 194.70;
    std::cout << "RearObject_.Properties[8].length(float32): " << RearObject_.Properties[8].length << std::endl;
    RearObject_.Properties[8].confidence = 42;
    std::cout << "RearObject_.Properties[8].confidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[8].confidence) << std::dec  << std::endl;
    RearObject_.Properties[8].type = 43;
    std::cout << "RearObject_.Properties[8].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[8].type) << std::dec  << std::endl;
    RearObject_.Properties[8].width = 195.80;
    std::cout << "RearObject_.Properties[8].width(float32): " << RearObject_.Properties[8].width << std::endl;
    RearObject_.Properties[8].id = 44;
    std::cout << "RearObject_.Properties[8].id(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[8].id) << std::dec  << std::endl;
    RearObject_.Properties[8].trackStatus = 45;
    std::cout << "RearObject_.Properties[8].trackStatus(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[8].trackStatus) << std::dec  << std::endl;
    RearObject_.Properties[9].latPositionConfidence = 46;
    std::cout << "RearObject_.Properties[9].latPositionConfidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[9].latPositionConfidence) << std::dec  << std::endl;
    RearObject_.Properties[9].length = 196.90;
    std::cout << "RearObject_.Properties[9].length(float32): " << RearObject_.Properties[9].length << std::endl;
    RearObject_.Properties[9].confidence = 47;
    std::cout << "RearObject_.Properties[9].confidence(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[9].confidence) << std::dec  << std::endl;
    RearObject_.Properties[9].type = 48;
    std::cout << "RearObject_.Properties[9].type(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[9].type) << std::dec  << std::endl;
    RearObject_.Properties[9].width = 198.00;
    std::cout << "RearObject_.Properties[9].width(float32): " << RearObject_.Properties[9].width << std::endl;
    RearObject_.Properties[9].id = 49;
    std::cout << "RearObject_.Properties[9].id(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[9].id) << std::dec  << std::endl;
    RearObject_.Properties[9].trackStatus = 50;
    std::cout << "RearObject_.Properties[9].trackStatus(uint8): " << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(RearObject_.Properties[9].trackStatus) << std::dec  << std::endl;
    RearObject_.SequenceID = 1;
    std::cout << "RearObject_.SequenceID(uint32): " << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(RearObject_.SequenceID) << std::dec  << std::endl;
}







